### ISSUE TITLE
sct_apply_transfo: adding integrity testing shows failure of 4D warping

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1962] opened 2018-07-24 04:02 UTC
### Description

While adding basic integrity testing to `sct_apply_transfo` I noticed that in the second test (warping a DMRI 4D image) is resulting in an image with only zeros, AFAIK this is probably caused by the spatial extents of the 2 images being too far away and the warping field being inadapted (the same as the one for the first test).

### Steps to Reproduce

0. Install SCT (from today)

1. Augment `testing/test_sct_apply_transfo.py` to look like this:  
```python
import os
import numpy as np
import sct_utils as sct
import msct_image

...

def test_integrity(param_test):
    """
    Test integrity of function
    """

    fname_src = param_test.dict_args_with_path["-i"]
    fname_ref = param_test.dict_args_with_path["-d"]
    fname_dst = "output.nii.gz"
    img_src = msct_image.Image(fname_src)
    img_ref = msct_image.Image(fname_ref)
    img_dst = msct_image.Image(fname_dst)

    if img_dst.orientation != img_ref.orientation:
        param_test.output += "\nImage has wrong orientation (%s -> %s)" \
         % (img_ref.orientation, img_dst.orientation)
        param_test.status = 1

    #if len(img_src.data.shape) == 4:
    #    # Allowed failure for now?
    #    return param_test

    if not (img_dst.data != 0).any():
        param_test.output += "\nImage is garbage (all zeros)"
        param_test.status = 1

    return param_test
```

2. Run `sct_testing  --execution-folder clean -f sct_apply_transfo`

**Expected behavior:** OK

**Actual behavior:** *Image is garbage (all zeros)*

**Comment by joshuacwnewton** [comment] 2020-10-11 17:50
`test_sct_apply_transfo` now checks for this and there is no error. I presume the root cause of the error was addressed without closing this issue.

**Closed by joshuacwnewton** 2020-10-11 17:50 UTC
Labels: tests
