### ISSUE TITLE
dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2591] opened 2020-01-28 15:51 UTC
This error seems to happen in particular OS/hardware. User post [here](http://forum.spinalcordmri.org/t/problem-with-latest-version-installation/311/4).

Possibly related to https://github.com/neuropoly/spinalcordtoolbox/issues/2541#issuecomment-560462364 and https://github.com/neuropoly/spinalcordtoolbox/issues/1620.

The user has the following OS:
~~~
Linux-3.16.0-4-amd64-x86_64-with-debian-8.11
~~~

Related issues (external):
- https://github.com/scikit-learn/scikit-learn/issues/14485
- https://github.com/pytorch/pytorch/issues/2575

**Comment by jcohenadad** [comment] 2020-02-10 17:52
Interestingly, SCT version 4.0.0 does not produce the error (at least for the user's post referred to above).

**Comment by alexfoias** [comment] 2020-02-11 15:51
I managed to reproduce the error on a VM. Output here:
https://gist.github.com/alexfoias/60d39457d33ffd33d281a6392fcf0d6d

**Comment by jcohenadad** [comment] 2020-02-11 15:54
thanks @alexfoias, can you try now with v4.0.0

**Comment by alexfoias** [comment] 2020-02-11 17:10
The installation also fails for v 4.0.0

Here is the output: https://gist.github.com/alexfoias/7a77a802cb8cea444506af07342094d9

**Comment by jcohenadad** [comment] 2020-02-11 17:14
Thank you Alex. Hum... what's concerning is that this is not consistent with what the user is reporting. I'll contact her to get more details.

**Comment by jcohenadad** [comment] 2020-03-20 19:56
Related to https://github.com/neuropoly/spinalcordtoolbox/issues/2541

**Comment by joshuacwnewton** [comment] 2021-05-03 13:44
We've encountered this again here: https://forum.spinalcordmri.org/t/issue-when-installing-sct-5-3-0/696/4

I believe the issue is due to Debian 8, which contains an outdated version of GLIBC. There is a bugfix for this issue (see https://github.com/scikit-learn/scikit-learn/issues/14485#issuecomment-822678559), but it was included in GLIBC 2.21, and Debian 8 machines have an older version of GLIBC.

We don't currently test against Debian 8, as Debian 8 has reached “end of life” status and no longer receives security updates from Debian. So, I think the best solution in this case is to encourage users to upgrade their OS.

I'm going to dig a bit to see if there's a workaround, though.

**Comment by jcohenadad** [comment] 2021-05-03 14:03
> So, I think the best solution in this case is to encourage users to upgrade their OS.

typical situation in an academic lab:
- ITs put together computer infrastructure with old OSs (Debian 8, centOS 7, etc.)
- These computers are supposed to serve members of the lab (researchers, students)
- OSs are not upgraded often, partly because it could cause cross-compatibility issues, or worse: different results on an analysis pipeline. So ppl usually prefer to keep the status quo in fear of introducing different results in a longitudinal neuroimaging study.
- Young members of the lab (typically MSc students) are usually scared of emailing ITs to ask for an upgrade of OSs, and PIs don't do it because they are not aware of the problem.

**Comment by joshuacwnewton** [comment] 2021-05-03 14:06
Ah, thank you for the additional context. Using docker/singularity as a workaround makes a lot more sense now.

**Comment by joshuacwnewton** [comment] 2021-05-06 13:55
As an update, they have tried Docker, and they're now able to use SCT (I assume, based on their follow-up bvals question).

I'm going to close this issue, as we now understand the cause (outdated OS), and we have a good recommendation for any users who encounter this.

**Closed by joshuacwnewton** 2021-05-06 13:55 UTC
Labels: installation
