### ISSUE TITLE
sct_label_utils: IndexError: index 118 is out of bounds for axis 2 with size 118 

### ISSUE THREAD

**Issue by felixsc1** [neuropoly/spinalcordtoolbox#2424] opened 2019-08-30 10:51 UTC
When using a segmentation file as input.  

syntax:
`sct_label_utils -i nifti_seg.nii.gz -create-seg 0,14:117,8`

```
> Spinal Cord Toolbox (git-master-ff7553098ea27d2b6a51a90965a526f53368805e*)
> 
> Traceback (most recent call last): 
>   File "/home/felix/Repos/sct/scripts/sct_label_utils.py", line 828, in <module>
>     main()
>   File "/home/felix/Repos/sct/scripts/sct_label_utils.py", line 818, in main
>     processor.process(process_type)
>   File "/home/felix/Repos/sct/scripts/sct_label_utils.py", line 112, in process
>     self.output_image = self.create_label_along_segmentation()
>   File "/home/felix/Repos/sct/scripts/sct_label_utils.py", line 215, in create_label_along_segmentation
>     x, y = ndimage.measurements.center_of_mass(np.array(im_rpi.data[:, :, z_rpi]))
> IndexError: index 118 is out of bounds for axis 2 with size 118 
```

**Comment by jcohenadad** [comment] 2019-08-30 16:05
@felixsc1 thank you for reporting this bug.

It sounds like the algo is trying to compute a center of mass in an empty slice. Maybe you have "holes" in your segmentation?  I'm happy to look at the problem if you upload the segmentation.

**Comment by felixsc1** [comment] 2019-08-30 18:56
Thanks, I did have an empty slice in the segmentation, but after fixing it I still get the error.
[Here](https://1drv.ms/u/s!Aq6XXK3CMI1M7w-C3Gp3Bul2LYDU?e=yUNihr) is the example segmentation file. I get the error also for other scans of the same geometry.

**Comment by jcohenadad** [comment] 2019-08-30 19:47
@felixsc1 this is because the function assumes that the 3rd dimension of your input image (z) corresponds to the superior-inferior axis, which is not the case here (your 3rd dimension is A-P). So first, you would need to reorient to e.g. RPI, and then get your labels:
~~~
sct_image -i T1_seg.nii.gz -setorient RPI -o T1_seg_RPI.nii.gz
sct_label_utils -i T1_seg_RPI.nii.gz -create-seg 0,14:106,8
~~~

We will add a check at the beginning of the function, to make sure the input image is in the correct orientation.

**Comment by jcohenadad** [comment] 2019-08-31 15:54
reopening to make sure we implement the check for orientation of the input image

**Comment by joshuacwnewton** [comment] 2020-11-09 18:54
In #2289, the following was added to the `create_label_along_segmentation` function:

https://github.com/neuropoly/spinalcordtoolbox/blob/3d5df3e9b9c1de2047f463ab2189a4b72c4947c1/scripts/sct_label_utils.py#L195-L196

This has since been refactored during #2887 to the following:

https://github.com/neuropoly/spinalcordtoolbox/blob/d310d2670f93f0c272efc3e33a5e07b922d05230/spinalcordtoolbox/labels.py#L101-L104

So, the orientation check mentioned by @jcohenadad (https://github.com/neuropoly/spinalcordtoolbox/issues/2424#issuecomment-526841432) is already in place. 

The curious thing is, the conversion to `RPI` was already been in place by the time this problem was reported (#2289: May 2019 vs. #2424: October 2019). So, I'm not sure what the cause of the original issue was.

Still, I think we could possibly close this.

**Comment by jcohenadad** [comment] 2020-11-09 19:00
The issue is more perverse than that: in the input syntax, the orientation is assumed to have z as the last dimension (chunk that says "0,14:106,8"). Even if data are reoriented, what counts is what the user think is the inferior-superior dimension.

**Comment by joshuacwnewton** [comment] 2020-11-09 19:11
Ah, I see now. I was going off of just these comments (https://github.com/neuropoly/spinalcordtoolbox/issues/2424#issuecomment-526726179) but more analysis was done in @saulo-p's PR here: https://github.com/neuropoly/spinalcordtoolbox/pull/2710#issuecomment-638408235. 

I will look further into this to pick up where @saulo-p left off.

**Comment by joshuacwnewton** [comment] 2020-11-09 19:36
> Even if data are reoriented, what counts is what the user think is the inferior-superior dimension.

In that case, is this issue not just an isolated case of usage error? i.e. if the input here was supposed to be `0,14:106,8` instead of `0,14:117,8`. Or am I still misunderstanding?

**Comment by jcohenadad** [comment] 2020-11-09 19:42
I would need to spend a few minutes looking at the usage/code of this function, but a quick glance raises a few flags:
- the systematic reorientation to RPI might not be needed for some operations, e.g. `-add`, `-display`
- wrt. the issue raised by the user in this thread: I agree this is an isolated case, but i could think of two improvements:
  - change the usage of `-create-seg` to replace "z" by "slice index in the inferior-superior direction (e.g. z in case the image is oriented as RPI)"
  - display a warning in case the last dim is not I or S.

these are my "quick" two-cent

**Comment by joshuacwnewton** [comment] 2020-11-09 19:49
Perfect, I think we are on the same page. :slightly_smiling_face: 

I very much agree that improvements could definitely be made to make the proper usage of `-create-seg` more clear.

**Closed** 2020-11-11 15:09 UTC
Labels: bug, priority:HIGH, sct_label_utils
