### ISSUE TITLE
Cropping is setting a wrong qform factor

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2454] opened 2019-09-25 17:37 UTC
### Description

When cropping an image using `sct_crop_image`, the output qform code is wrongly set to 2 (Aligned Anat), which goes against the [Nifti convention](https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/qsform_brief_usage), specifying that the qform_code should be either 0 or 1.

Moreover, the output sform_name and sform_code are inconsistent: it gives 
~~~
sform_name	Aligned Anat
sform_code	1  # ERROR! This code should correspond to Scanner Anat
~~~

I have not investigated if this issue is systematic.

Useful links:
- https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F
- https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/qsform.html
- https://nipy.org/nibabel/nifti_images.html#the-qform-affine

Related to #2429.

### Steps to Reproduce

SCT commit: 

~~~
cd sct_testing_data/mt
sct_crop_image -i mt1.nii.gz -ymin 2 -ymax 1 -o mt1_crop.nii.gz
fslhd mt1
# --> qform_name	Scanner Anat
# --> qform_code	1
fslhd mt1_crop
# --> qform_name	Aligned Anat
# --> qform_code	2  # ERROR! Forbidden value
~~~

**Comment by joshuacwnewton** [comment] 2021-03-08 21:13
Adding this to the `5.2.1` milestone to be discussed, because it is listed as high-priority and might be worth investigating prior to a patch release.

**Comment by joshuacwnewton** [comment] 2021-03-11 15:15
> Moreover, the output sform_name and sform_code are inconsistent: it gives
> 
> ```
> sform_name	Aligned Anat
> sform_code	1  # ERROR! This code should correspond to Scanner Anat
> ```

This is strange, because `fslhd` infers the name directly from the code. From [`fslhd.cc`](http://ftp.nmr.mgh.harvard.edu/pub/dist/freesurfer/tutorial_packages/OSX/fsl_501/src/avwutils/fslhd.cc):

```cpp
  cout << "sform_name     " << nifti_xform_string(fslio->niftiptr->sform_code) << endl;
  cout << "sform_code     " << fslio->niftiptr->sform_code << endl;
```

([Source for `nifti_xform_string`](http://niftilib.sourceforge.net/c_api_html/nifti1__io_8h.html#a32))

**Comment by joshuacwnewton** [comment] 2021-03-12 21:30
Hrm, I'm not able to reproduce. When calling 

```
cd sct_testing_data/mt
sct_crop_image -i mt1.nii.gz -ymin 2 -ymax 1 -o mt1_crop.nii.gz
fslhd mt1_crop.nii.gz
```

I get:

```
qform_name      Scanner Anat
qform_code      1
qto_xyz:1       -0.843379 -0.000000 -0.503756 10.726137 
qto_xyz:2       -0.001874 0.841376 1.273740 -15.558533 
qto_xyz:3       -0.024932 -0.063247 16.944729 -25.191698 
qto_xyz:4       0.000000 0.000000 0.000000 1.000000 
qform_xorient   Right-to-Left
qform_yorient   Posterior-to-Anterior
qform_zorient   Inferior-to-Superior
sform_name      Scanner Anat
sform_code      1
sto_xyz:1       -0.843379 0.000000 -0.503807 10.726137 
sto_xyz:2       -0.001874 0.841376 1.273740 -15.558533 
sto_xyz:3       -0.024935 -0.063247 16.944727 -25.191698 
sto_xyz:4       0.000000 0.000000 0.000000 1.000000 
sform_xorient   Right-to-Left
sform_yorient   Posterior-to-Anterior
sform_zorient   Inferior-to-Superior
file_type       NIFTI-1+
file_code       1
descrip         FSL5.0
aux_file    
```

**Comment by joshuacwnewton** [comment] 2021-03-12 21:35
One thing we could do for peace of mind is add a check + warning for `qform_code==2` in `Image.save()`.

**Comment by jcohenadad** [comment] 2021-03-12 21:53
> Hrm, I'm not able to reproduce. When calling

maybe it has been fixed (the issue is fairly old-- sept 2019)

**Comment by joshuacwnewton** [comment] 2021-03-23 14:11
> > Hrm, I'm not able to reproduce. When calling
> 
> maybe it has been fixed (the issue is fairly old-- sept 2019)

For now, I'm going to close this. 

Checking for other instances of `qform_code==2` is beyond the scope of this issue, and can be handled as part of #3283.

**Closed by joshuacwnewton** 2021-03-23 14:11 UTC
Labels: priority:HIGH, sct_crop_image
