### ISSUE TITLE
Introducing QC reports for moco functions

### ISSUE THREAD

**Issue by peristeri** [neuropoly/spinalcordtoolbox#1343] opened 2017-05-26 21:29 UTC
### Description

Functions such as `dmri_moco` and `fmri_moco` output 4D nifti images. To generate a QC report, we are suggesting an axial mosaic which loops across the 4th dimension (time). The overlay on the images should be a white grid to aide the visual assessment.

parameters:
- grid {0,1}: overlay white grid on top of the image for easier QC
- speed [s]: duration between two consecutive frames

### Design Decision

1.  Introduce a new parameter `-qc` to `sct_fmri_moco` and `sct_dmri_moco`
2. Add `Qc.Report` function to `sct_fmri_moco` and `sct_dmri_moco` similar to the implementation in `sct_propseg`
3. Extend the functionality of the `Slice` class. Add the function `mosaic_through_time` that will create a png mosaic of the input file and a list of png mosaic files ordered by time.

**Comment by jcohenadad** [comment] 2021-01-29 21:25
We might also consider changing our QC report technology https://github.com/neuropoly/spinalcordtoolbox/issues/1991

**Comment by joshuacwnewton** [comment] 2021-05-05 21:20
Realizing now that this is a duplicate of #3242, so closing it.

**Closed by joshuacwnewton** 2021-05-05 21:20 UTC
Labels: feature, good internship project, priority:MEDIUM, sct_dmri_moco, sct_fmri_moco, sct_qc
