### ISSUE TITLE
4.0.0-beta.3 installation fail

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/spinalcordtoolbox#2254] opened 2019-05-06 15:56 UTC
The user tried to install sct from the release 4.0.0-beta.3. He is running OSX El Capitan (10.11).

<details>

~~~

mingus:spinalcordtoolbox-4.0.0-beta.3 heyan_admin$ ./install_sct

Welcome to the SCT installer!

SCT version ......... 4.0.0-beta.3
Installation type ... package
Operating system .... osx
Shell ............... /Users/heyan_admin/.bashrc
sudo mode ........... 0

To improve user experience and fix bugs, the SCT development team is using a
report system to automatically receive crash reports and errors from users.
These reports are anonymous.
Do you agree to help us improve SCT? [y]es/[n]o: y
--> Crash reports will be sent to the SCT development team. Thank you!

SCT will be installed here: [/Users/heyan_admin/sct_4.0.0-beta.3]
Do you agree? [y]es/[n]o: y

Copying source files from /Users/heyan_admin/Desktop/SCT/spinalcordtoolbox-4.0.0-beta.3 to /Users/heyan_admin/sct_4.0.0-beta.3
....................................................................................................................................................................................................................................................................................................................................................................................................
Removing sct and isct softlink from /Users/heyan_admin/sct_4.0.0-beta.3/bin

Installing conda...
>> rm -rf /Users/heyan_admin/sct_4.0.0-beta.3/python
>> mkdir -p /Users/heyan_admin/sct_4.0.0-beta.3/python
>> curl -o /var/folders/2k/mgtxf9nj3311pzmnywdd93fr0000gs/T/tmp.Y7zHEDqO/miniconda.sh -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.0M  100 44.0M    0     0  10.6M      0  0:00:04  0:00:04 --:--:-- 10.6M
exit status is 0
>> bash /var/folders/2k/mgtxf9nj3311pzmnywdd93fr0000gs/T/tmp.Y7zHEDqO/miniconda.sh -p /Users/heyan_admin/sct_4.0.0-beta.3/python -b -f
PREFIX=/Users/heyan_admin/sct_4.0.0-beta.3/python
reinstalling: python-3.7.3-h359304d_0 ...
using -f (force) option
Python 3.7.3
reinstalling: ca-certificates-2019.1.23-0 ...
using -f (force) option
reinstalling: libcxxabi-4.0.1-hcfea43d_1 ...
using -f (force) option
reinstalling: xz-5.2.4-h1de35cc_4 ...
using -f (force) option
reinstalling: yaml-0.1.7-hc338f04_2 ...
using -f (force) option
reinstalling: zlib-1.2.11-h1de35cc_3 ...
using -f (force) option
reinstalling: libcxx-4.0.1-hcfea43d_1 ...
using -f (force) option
reinstalling: openssl-1.1.1b-h1de35cc_1 ...
using -f (force) option
reinstalling: tk-8.6.8-ha441bb4_0 ...
using -f (force) option
reinstalling: libffi-3.2.1-h475c297_4 ...
using -f (force) option
reinstalling: ncurses-6.1-h0a44026_1 ...
using -f (force) option
reinstalling: libedit-3.1.20181209-hb402a30_0 ...
using -f (force) option
reinstalling: readline-7.0-h1de35cc_5 ...
using -f (force) option
reinstalling: sqlite-3.27.2-ha441bb4_0 ...
using -f (force) option
reinstalling: asn1crypto-0.24.0-py37_0 ...
using -f (force) option
reinstalling: certifi-2019.3.9-py37_0 ...
using -f (force) option
reinstalling: chardet-3.0.4-py37_1 ...
using -f (force) option
reinstalling: idna-2.8-py37_0 ...
using -f (force) option
reinstalling: pycosat-0.6.3-py37h1de35cc_0 ...
using -f (force) option
reinstalling: pycparser-2.19-py37_0 ...
using -f (force) option
reinstalling: pysocks-1.6.8-py37_0 ...
using -f (force) option
reinstalling: python.app-2-py37_9 ...
using -f (force) option
reinstalling: ruamel_yaml-0.15.46-py37h1de35cc_0 ...
using -f (force) option
reinstalling: six-1.12.0-py37_0 ...
using -f (force) option
reinstalling: cffi-1.12.2-py37hb5b8e2f_1 ...
using -f (force) option
reinstalling: setuptools-41.0.0-py37_0 ...
using -f (force) option
reinstalling: cryptography-2.6.1-py37ha12b0ac_0 ...
using -f (force) option
reinstalling: wheel-0.33.1-py37_0 ...
using -f (force) option
reinstalling: pip-19.0.3-py37_0 ...
using -f (force) option
reinstalling: pyopenssl-19.0.0-py37_0 ...
using -f (force) option
reinstalling: urllib3-1.24.1-py37_0 ...
using -f (force) option
reinstalling: requests-2.21.0-py37_0 ...
using -f (force) option
reinstalling: conda-4.6.14-py37_0 ...
using -f (force) option
using -f (force) option
installation finished.
Conda installation successful
>> . /Users/heyan_admin/sct_4.0.0-beta.3/python/bin/activate /Users/heyan_admin/sct_4.0.0-beta.3/python
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/heyan_admin/sct_4.0.0-beta.3/python

  added / updated specs:
    - anaconda-client


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anaconda-client-1.7.2      |             py_0          69 KB  conda-forge
    attrs-19.1.0               |             py_0          32 KB  conda-forge
    ca-certificates-2019.3.9   |       hecc5488_0         146 KB  conda-forge
    certifi-2019.3.9           |           py37_0         149 KB  conda-forge
    clyent-1.2.2               |             py_1           9 KB  conda-forge
    conda-4.6.14               |           py37_0         2.1 MB  conda-forge
    decorator-4.4.0            |             py_0          11 KB  conda-forge
    ipython_genutils-0.2.0     |             py_1          21 KB  conda-forge
    jsonschema-3.0.1           |           py37_0          85 KB  conda-forge
    jupyter_core-4.4.0         |             py_0          44 KB  conda-forge
    nbformat-4.4.0             |             py_1          91 KB  conda-forge
    openssl-1.1.1b             |       h01d97ff_2         3.5 MB  conda-forge
    pyrsistent-0.15.1          |   py37h01d97ff_0          86 KB  conda-forge
    python-dateutil-2.8.0      |             py_0         219 KB  conda-forge
    pytz-2019.1                |             py_0         227 KB  conda-forge
    pyyaml-5.1                 |   py37h1de35cc_0         165 KB  conda-forge
    traitlets-4.3.2            |        py37_1000         130 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         7.0 MB

The following NEW packages will be INSTALLED:

  anaconda-client    conda-forge/noarch::anaconda-client-1.7.2-py_0
  attrs              conda-forge/noarch::attrs-19.1.0-py_0
  clyent             conda-forge/noarch::clyent-1.2.2-py_1
  decorator          conda-forge/noarch::decorator-4.4.0-py_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  jsonschema         conda-forge/osx-64::jsonschema-3.0.1-py37_0
  jupyter_core       conda-forge/noarch::jupyter_core-4.4.0-py_0
  nbformat           conda-forge/noarch::nbformat-4.4.0-py_1
  pyrsistent         conda-forge/osx-64::pyrsistent-0.15.1-py37h01d97ff_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  pytz               conda-forge/noarch::pytz-2019.1-py_0
  pyyaml             conda-forge/osx-64::pyyaml-5.1-py37h1de35cc_0
  traitlets          conda-forge/osx-64::traitlets-4.3.2-py37_1000

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.1.23-0 --> conda-forge::ca-certificates-2019.3.9-hecc5488_0
  openssl              pkgs/main::openssl-1.1.1b-h1de35cc_1 --> conda-forge::openssl-1.1.1b-h01d97ff_2

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                         pkgs/main --> conda-forge
  conda                                           pkgs/main --> conda-forge



Downloading and Extracting Packages
clyent-1.2.2         | 9 KB      | ##################################### | 100% 
ipython_genutils-0.2 | 21 KB     | ##################################### | 100% 
pyrsistent-0.15.1    | 86 KB     | ##################################### | 100% 
jupyter_core-4.4.0   | 44 KB     | ##################################### | 100% 
pyyaml-5.1           | 165 KB    | ##################################### | 100% 
attrs-19.1.0         | 32 KB     | ##################################### | 100% 
openssl-1.1.1b       | 3.5 MB    | ##################################### | 100% 
pytz-2019.1          | 227 KB    | ##################################### | 100% 
decorator-4.4.0      | 11 KB     | ##################################### | 100% 
certifi-2019.3.9     | 149 KB    | ##################################### | 100% 
ca-certificates-2019 | 146 KB    | ##################################### | 100% 
python-dateutil-2.8. | 219 KB    | ##################################### | 100% 
traitlets-4.3.2      | 130 KB    | ##################################### | 100% 
conda-4.6.14         | 2.1 MB    | ##################################### | 100% 
anaconda-client-1.7. | 69 KB     | ##################################### | 100% 
jsonschema-3.0.1     | 85 KB     | ##################################### | 100% 
nbformat-4.4.0       | 91 KB     | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Warning: 'conda-forge' already in 'channels' list, moving to the top

Installing Python dependencies...
Collecting numpy
  Using cached https://files.pythonhosted.org/packages/43/6e/71a3af8680a159a141fab5b4d19988111a09c02ffbfdeb42175cca0fa341/numpy-1.16.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.16.3
Requirement already satisfied: numpy in ./python/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.16.3)
Requirement already satisfied: cryptography in ./python/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.6.1)
Collecting dipy (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/e4/31/2ca86ff2c01ba22e090b4f55db08c3d8e9efdebc8938a876e317e0a4d006/dipy-0.16.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting futures (from -r requirements.txt (line 4))
Collecting h5py (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/80/c5/eec74d7324628f1b640c6e706981c4ed51afcaa1656ece26cb08d862598e/h5py-2.9.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting Keras (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
Collecting matplotlib (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/2e/81/bb51214944e79f9c9261badd7ef99b573fb0bc9110c0075c6a9e76224d0d/matplotlib-3.0.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting nibabel (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/93/ed/35768f663a361030233a2357de0a482ea46e246af4fc9817dcd5273ee3a7/nibabel-2.4.0-py3-none-any.whl
Collecting pandas (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/fc/43/fd867e3347559845c8f993059d410c50a1e18709f1c4d4b3b47323a06a37/pandas-0.24.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting psutil (from -r requirements.txt (line 10))
Collecting pyqt5 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/2a/d3/c9fe729ef7fbcfa05804c84c359cf844e48b34a399a9601530b2235ce570/PyQt5-5.12.1-5.12.2-cp35.cp36.cp37.cp38-abi3-macosx_10_6_intel.whl
Collecting raven (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/bd/8e/62e26a88c0a1bbae677200baf0767c1022321a6555634f8129e6d55c5ddc/raven-6.10.0-py2.py3-none-any.whl
Requirement already satisfied: requests in ./python/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (2.21.0)
Collecting scipy (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/dd/6c/ccf7403d14f0ab0f20ce611696921f204f4ffce99a4fd383c892a6a7e9eb/scipy-1.2.1-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scikit-image (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/6f/ee/37254a96f7910f4caa830faad72a2fb144e1cebe62a5abbe50a80e942094/scikit_image-0.15.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting scikit-learn (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/bd/1a/5dc99dfa7e7bf2e1f22a07f440b61299148a42d13dee1d5153360313ed67/scikit_learn-0.20.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting tensorflow (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/d5/1c/3ac472009a5c54ae7ec5a3294520ca36d1908cd1e5cf3e3fd923f9b7b31f/tensorflow-1.13.1-cp37-cp37m-macosx_10_11_x86_64.whl
Collecting xlrd (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/b0/16/63576a1a001752e34bf8ea62e367997530dc553b689356b9879339cf45a4/xlrd-1.2.0-py2.py3-none-any.whl
Collecting xlutils (from -r requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/c7/55/e22ac73dbb316cabb5db28bef6c87044a95914f713a6e81b593f8a0d2f79/xlutils-2.0.0-py2.py3-none-any.whl
Collecting xlwt (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/44/48/def306413b25c3d01753603b1a222a011b8621aed27cd7f89cbc27e6b0f4/xlwt-1.3.0-py2.py3-none-any.whl
Collecting tqdm (from -r requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl
Collecting transforms3d (from -r requirements.txt (line 22))
Requirement already satisfied: urllib3[secure] in ./python/lib/python3.7/site-packages (from -r requirements.txt (line 23)) (1.24.1)
Collecting nipy (from -r requirements.txt (line 24))
Requirement already satisfied: six>=1.4.1 in ./python/lib/python3.7/site-packages (from cryptography->-r requirements.txt (line 2)) (1.12.0)
Requirement already satisfied: asn1crypto>=0.21.0 in ./python/lib/python3.7/site-packages (from cryptography->-r requirements.txt (line 2)) (0.24.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./python/lib/python3.7/site-packages (from cryptography->-r requirements.txt (line 2)) (1.12.2)
Collecting keras-applications>=1.0.6 (from Keras->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/90/85/64c82949765cfb246bbdaf5aca2d55f400f792655927a017710a78445def/Keras_Applications-1.0.7-py2.py3-none-any.whl
Requirement already satisfied: pyyaml in ./python/lib/python3.7/site-packages (from Keras->-r requirements.txt (line 6)) (5.1)
Collecting keras-preprocessing>=1.0.5 (from Keras->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/c0/bf/0315ef6a9fd3fc2346e85b0ff1f5f83ca17073f2c31ac719ab2e4da0d4a3/Keras_Preprocessing-1.0.9-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.1 in ./python/lib/python3.7/site-packages (from matplotlib->-r requirements.txt (line 7)) (2.8.0)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/df/93/8bc9b52a8846be2b9572aa0a7c881930939b06e4abe1162da6a0430b794f/kiwisolver-1.1.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting cycler>=0.10 (from matplotlib->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: pytz>=2011k in ./python/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 9)) (2019.1)
Collecting PyQt5_sip<4.20,>=4.19.14 (from pyqt5->-r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/be/f9/fbb132c459404222a97a0c151b45ccb1bfa9737a7966b40a8497da261fa3/PyQt5_sip-4.19.15-cp37-cp37m-macosx_10_6_intel.whl
Requirement already satisfied: certifi>=2017.4.17 in ./python/lib/python3.7/site-packages (from requests->-r requirements.txt (line 13)) (2019.3.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./python/lib/python3.7/site-packages (from requests->-r requirements.txt (line 13)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./python/lib/python3.7/site-packages (from requests->-r requirements.txt (line 13)) (2.8)
Collecting pillow>=4.3.0 (from scikit-image->-r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/22/55/2ce41fa510f131c776112a1d24ee90cddffc96f1bf0311efb14fdd8ae877/Pillow-6.0.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting PyWavelets>=0.4.0 (from scikit-image->-r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/1e/c5/7267d62da464851bd4b63f0da321acd949421079db341c3d059a31bbcb6a/PyWavelets-1.0.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting networkx>=2.0 (from scikit-image->-r requirements.txt (line 15))
Collecting imageio>=2.0.1 (from scikit-image->-r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/af/0a/943c965d372dae0b1f1482677d29030ab834351a61a9a632fd62f27f1523/imageio-2.5.0-py3-none-any.whl
Collecting protobuf>=3.6.1 (from tensorflow->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/d7/08/a316e74d41a1f3d606dfc3b71cc068354e8b9a0232f46bc098aa50b37116/protobuf-3.7.1-cp37-cp37m-macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting tensorboard<1.14.0,>=1.13.0 (from tensorflow->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/0f/39/bdd75b08a6fba41f098b6cb091b9e8c7a80e1b4d679a581a0ccd17b10373/tensorboard-1.13.1-py3-none-any.whl
Collecting grpcio>=1.8.6 (from tensorflow->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/c1/82/60d5ec84dd2ed474aced1a1fd3cff932306c359ce97b2bb3ff5bc750d0d9/grpcio-1.20.1-cp37-cp37m-macosx_10_9_x86_64.whl
Collecting termcolor>=1.1.0 (from tensorflow->-r requirements.txt (line 17))
Requirement already satisfied: wheel>=0.26 in ./python/lib/python3.7/site-packages (from tensorflow->-r requirements.txt (line 17)) (0.33.1)
Collecting gast>=0.2.0 (from tensorflow->-r requirements.txt (line 17))
Collecting absl-py>=0.1.6 (from tensorflow->-r requirements.txt (line 17))
Collecting astor>=0.6.0 (from tensorflow->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/35/6b/11530768cac581a12952a2aad00e1526b89d242d0b9f59534ef6e6a1752f/astor-0.7.1-py2.py3-none-any.whl
Collecting tensorflow-estimator<1.14.0rc0,>=1.13.0 (from tensorflow->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/bb/48/13f49fc3fa0fdf916aa1419013bb8f2ad09674c275b4046d5ee669a46873/tensorflow_estimator-1.13.0-py2.py3-none-any.whl
Requirement already satisfied: pyOpenSSL>=0.14 in ./python/lib/python3.7/site-packages (from urllib3[secure]->-r requirements.txt (line 23)) (19.0.0)
Collecting ipaddress (from urllib3[secure]->-r requirements.txt (line 23))
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting sympy>=0.7.0 (from nipy->-r requirements.txt (line 24))
  Using cached https://files.pythonhosted.org/packages/21/21/f4105795ca7f35c541d82c5b06be684dd2f5cb4f508fb487cd7aea4de776/sympy-1.4-py2.py3-none-any.whl
Requirement already satisfied: pycparser in ./python/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->-r requirements.txt (line 2)) (2.19)
Requirement already satisfied: setuptools in ./python/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->-r requirements.txt (line 7)) (41.0.0)
Requirement already satisfied: decorator>=4.3.0 in ./python/lib/python3.7/site-packages (from networkx>=2.0->scikit-image->-r requirements.txt (line 15)) (4.4.0)
Collecting markdown>=2.6.8 (from tensorboard<1.14.0,>=1.13.0->tensorflow->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/f5/e4/d8c18f2555add57ff21bf25af36d827145896a07607486cc79a2aea641af/Markdown-3.1-py2.py3-none-any.whl
Collecting werkzeug>=0.11.15 (from tensorboard<1.14.0,>=1.13.0->tensorflow->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/18/79/84f02539cc181cdbf5ff5a41b9f52cae870b6f632767e43ba6ac70132e92/Werkzeug-0.15.2-py2.py3-none-any.whl
Collecting mock>=2.0.0 (from tensorflow-estimator<1.14.0rc0,>=1.13.0->tensorflow->-r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/42/b4/f9afb3de9bd92d165e94a81f4048b373825009be9234f588a69afc64e7a1/mock-3.0.4-py2.py3-none-any.whl
Collecting mpmath>=0.19 (from sympy>=0.7.0->nipy->-r requirements.txt (line 24))
Installing collected packages: nibabel, h5py, scipy, dipy, futures, keras-applications, keras-preprocessing, Keras, pyparsing, kiwisolver, cycler, matplotlib, pandas, psutil, PyQt5-sip, pyqt5, raven, pillow, PyWavelets, networkx, imageio, scikit-image, scikit-learn, protobuf, markdown, absl-py, grpcio, werkzeug, tensorboard, termcolor, gast, astor, mock, tensorflow-estimator, tensorflow, xlrd, xlwt, xlutils, tqdm, transforms3d, mpmath, sympy, nipy, ipaddress
Successfully installed Keras-2.2.4 PyQt5-sip-4.19.15 PyWavelets-1.0.3 absl-py-0.7.1 astor-0.7.1 cycler-0.10.0 dipy-0.16.0 futures-3.1.1 gast-0.2.2 grpcio-1.20.1 h5py-2.9.0 imageio-2.5.0 ipaddress-1.0.22 keras-applications-1.0.7 keras-preprocessing-1.0.9 kiwisolver-1.1.0 markdown-3.1 matplotlib-3.0.3 mock-3.0.4 mpmath-1.1.0 networkx-2.3 nibabel-2.4.0 nipy-0.4.2 pandas-0.24.2 pillow-6.0.0 protobuf-3.7.1 psutil-5.6.2 pyparsing-2.4.0 pyqt5-5.12.1 raven-6.10.0 scikit-image-0.15.0 scikit-learn-0.20.3 scipy-1.2.1 sympy-1.4 tensorboard-1.13.1 tensorflow-1.13.1 tensorflow-estimator-1.13.0 termcolor-1.1.0 tqdm-4.31.1 transforms3d-0.3.1 werkzeug-0.15.2 xlrd-1.2.0 xlutils-2.0.0 xlwt-1.3.0
Obtaining file:///Users/heyan_admin/sct_4.0.0-beta.3
Installing collected packages: spinalcordtoolbox
  Running setup.py develop for spinalcordtoolbox
Successfully installed spinalcordtoolbox

Creating launchers for Python scripts...

Installing binaries...
>> sct_download_data -d binaries_osx -o /Users/heyan_admin/sct_4.0.0-beta.3/bin
Folder /Users/heyan_admin/sct_4.0.0-beta.3/bin has been created.

Trying URL: https://osf.io/zjv4c/?action=download
Downloading 20181204_sct_binaries_osx.tar.gz...
Status: 100%|##############################| 68.7M/68.7M [00:05<00:00, 11.5MB/s]

Check if folder already exists...

Unzip data to: /Users/heyan_admin/sct_4.0.0-beta.3/bin

Remove temporary file...
Done!

All requirements installed!
>> . /Users/heyan_admin/sct_4.0.0-beta.3/python/bin/activate /Users/heyan_admin/sct_4.0.0-beta.3/python

Installing data...
>> rm -rf /Users/heyan_admin/sct_4.0.0-beta.3/data
>> mkdir -p /Users/heyan_admin/sct_4.0.0-beta.3/data
>> cd /Users/heyan_admin/sct_4.0.0-beta.3/data
>> sct_download_data -d PAM50

Trying URL: https://osf.io/kc3jx/?action=download
Downloading 20181214_PAM50.zip...
Status: 100%|##############################| 70.8M/70.8M [00:09<00:00, 7.64MB/s]

Check if folder already exists...

Unzip data to: /Users/heyan_admin/sct_4.0.0-beta.3/data

Remove temporary file...
Done!

>> sct_download_data -d gm_model

Trying URL: https://osf.io/ugscu/?action=download
Downloading 20160922_gm_model.zip...
Status: 100%|##############################| 10.3M/10.3M [00:00<00:00, 10.9MB/s]

Check if folder already exists...

Unzip data to: /Users/heyan_admin/sct_4.0.0-beta.3/data

Remove temporary file...
Done!

>> sct_download_data -d optic_models

Trying URL: https://osf.io/g4fwn/?action=download
Downloading 20170413_optic_models.zip...
Status: 100%|##############################| 17.7k/17.7k [00:00<00:00, 19.1MB/s]

Check if folder already exists...

Unzip data to: /Users/heyan_admin/sct_4.0.0-beta.3/data

Remove temporary file...
Done!

>> sct_download_data -d pmj_models

Trying URL: https://osf.io/4gufr/?action=download
Downloading 20170922_pmj_models.zip...
Status: 100%|##############################| 8.87k/8.87k [00:00<00:00, 18.0MB/s]

Check if folder already exists...

Unzip data to: /Users/heyan_admin/sct_4.0.0-beta.3/data

Remove temporary file...
Done!

>> sct_download_data -d deepseg_sc_models

Trying URL: https://osf.io/avf97/?action=download
Downloading 20180610_deepseg_sc_models.zip...
Status: 100%|##############################| 58.7M/58.7M [00:05<00:00, 11.6MB/s]

Check if folder already exists...

Unzip data to: /Users/heyan_admin/sct_4.0.0-beta.3/data

Remove temporary file...
Done!

>> sct_download_data -d deepseg_gm_models

Trying URL: https://osf.io/b9y4x/?action=download
Downloading 20180205_deepseg_gm_models.zip...
Status: 100%|##############################| 2.28M/2.28M [00:00<00:00, 8.59MB/s]

Check if folder already exists...

Unzip data to: /Users/heyan_admin/sct_4.0.0-beta.3/data

Remove temporary file...
Done!

>> sct_download_data -d deepseg_lesion_models

Trying URL: https://osf.io/eg7v9/?action=download
Downloading 20180613_deepseg_lesion_models.zip...
Status: 100%|##############################| 16.0M/16.0M [00:01<00:00, 11.3MB/s]

Check if folder already exists...

Unzip data to: /Users/heyan_admin/sct_4.0.0-beta.3/data

Remove temporary file...
Done!

>> sct_download_data -d c2c3_disc_models

Trying URL: https://osf.io/t97ap/?action=download
Downloading 20190117_c2c3_disc_models.zip...
Status: 100%|##############################| 8.94k/8.94k [00:00<00:00, 18.7MB/s]

Check if folder already exists...

Unzip data to: /Users/heyan_admin/sct_4.0.0-beta.3/data

Remove temporary file...
Done!


Do you want to add the sct_* scripts to your PATH environment? [y]es/[n]o: y


Validate installation...
SCT info:
- version: 4.0.0-beta.3
- path: /Users/heyan_admin/sct_4.0.0-beta.3
OS: osx (Darwin-15.6.0-x86_64-i386-64bit)
CPU cores: Available: 4, Used by SCT: 4
RAM: Primary memory available: 12.00 gigabytes
Check Python executable.............................[OK]
  Using bundled python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] at /Users/heyan_admin/sct_4.0.0-beta.3/python/bin/python
Check if data are installed.........................[OK]
Check if numpy is installed.........................[OK] (1.16.3)
Check if cryptography is installed..................[OK] (2.6.1)
Check if dipy is installed..........................[OK] (0.16.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.9.0)
Check if Keras is installed.........................[FAIL]
Check if matplotlib is installed....................[OK] (3.0.3)
Check if nibabel is installed.......................[OK] (2.4.0)
Check if pandas is installed........................[OK] (0.24.2)
Check if psutil is installed........................[OK] (5.6.2)
Check if pyqt5 is installed.........................[OK]
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.21.0)
Check if scipy is installed.........................[OK] (1.2.1)
Check if scikit-image is installed..................[OK] (0.15.0)
Check if scikit-learn is installed..................[OK] (0.20.3)
Check if tensorflow is installed....................[FAIL]
Check if xlrd is installed..........................[OK] (1.2.0)
Check if xlutils is installed.......................[OK]
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.31.1)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3[secure] is installed...............[OK] (1.24.1)
Check if nipy is installed..........................[OK] (0.4.2)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if figure can be opened.......................[OK]

Installation validation Failed!
Please copy the historic of this Terminal (starting with the command install_sct) and paste it in the SCT Help forum (create a new discussion):
http://forum.spinalcordmri.org/c/sct

Installation failed

~~~

</details>

**Comment by jcohenadad** [comment] 2019-05-06 19:50
TF supported as of 10.12. See: https://www.tensorflow.org/install/pip

Pls upgrade to 10.12 or higher

**Comment by jcohenadad** [comment] 2019-06-11 14:33
duplicate of https://github.com/neuropoly/spinalcordtoolbox/issues/2302

**Closed by jcohenadad** 2019-06-11 14:33 UTC
