### ISSUE TITLE
Slice navigator crashes using arrow keys 

### ISSUE THREAD

**Issue by agahkarakuzu** [neuropoly/spinalcordtoolbox#2447] opened 2019-09-19 02:34 UTC
# Description

When the requested slice number (e.g. 65) exceeds that of max available for the visualized volume (e.g. 64) while holding the right arrow key on the keyboard, `sct_label_utils` crashes. 

### Steps to Reproduce

0. SCT running on a centOS container. Please see https://github.com/neuropoly/spinalcordtoolbox/issues/2436#issuecomment-532935963.

1. Use [sct_london_course_dataset](https://www.neuro.polymtl.ca/_media/downloads/sct/20190121_sct_course-london19.zip)

2.  `cd tmp/sct_course-london19/single_subject/data/t2`

3. `sct_label_utils -i t2.nii.gz -create-viewer 1,2,3,4,5,6,7 -o t2label`

4. Keep holding the right arrow key 

**Expected behavior:** 

Navigator should prevent further action. 

**Actual behavior:** 

![image](https://user-images.githubusercontent.com/9632322/65208893-648c1e80-da64-11e9-8a7d-26d4f658c860.png)

**Comment by jcohenadad** [comment] 2020-10-06 22:11
IIRC Saulo fixed that. Can someone try to reproduce this issue @joshuacwnewton @Drulex ?

**Comment by Drulex** [comment] 2020-10-08 15:35
Unable to reproduce. Closing.

**Closed by Drulex** 2020-10-08 15:35 UTC
