### ISSUE TITLE
Add init-centerline option into sct_deepseg_sc

### ISSUE THREAD

**Issue by valosekj** [neuropoly/spinalcordtoolbox#1985] opened 2018-08-06 11:43 UTC
Dear SCT experts,
_sct_deepseg_sc_ works generally  better than _sct_propseg_ on our data (mainly in patients with cervical myelopathy). But in some cases when patient has greater stenosis and contrast is lower in these levels segmentation fails. I found out that reason of it is bad centerline detection by _Optic_ alg. (I also tried to change -centerline detection method from svm to cnn, but result of segmentation  is empty image)
There is -init-centerline option in _propseg_ alg which I used when I had these problems to initialize the SC segmentation by manually created centerline, but this option is not available in _deepseg_. 
Haven't you thought about adding it?

![sct_deepseg_sc-segmentation_fails](https://user-images.githubusercontent.com/39456460/43714637-e9749d6c-997d-11e8-9de0-6eb94243ed51.png)

**Comment by jcohenadad** [comment] 2018-08-06 14:25
hi @valosekj, thank you for the feedback. Indeed, we agree and have already opened an issue: https://github.com/neuropoly/spinalcordtoolbox/issues/1952. I have just increased the priority level. We can close this issue (duplicate of #1952).

**Closed by jcohenadad** 2018-08-06 14:25 UTC

**Comment by valosekj** [comment] 2018-08-06 18:34
Hi @jcohenadad, thank you for response. It's nice to see you are working on it already. Sorry for duplication.

**Comment by charleygros** [comment] 2018-10-01 08:59
Hi @valosekj,

Apologies for the delay.

To add a manual centerline as input of `sct_deepseg_sc` is now available in the current version of the `master` branch of SCT and will be included in the next release.

To use it, please run:
```
sct_deepseg_sc -i t2.nii.gz -c t2 -centerline manual -file_centerline t2_centerline_manual.nii.gz
```
or you could also use the viewer to generate the centerline:
```
sct_deepseg_sc -i t2.nii.gz -c t2 -centerline viewer
```

Thank you for raising this point, really appreciated.
