### ISSUE TITLE
sct_segment_graymatter: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by nguyen1j** [neuropoly/spinalcordtoolbox#739] opened 2016-02-23 17:48 UTC
Command line
sct_segment_graymatter -i MTR0MTR1.nii -s MTR1_seg_crop.nii -vert MNI-Poly-AMU_level.nii.gz -qc 0

Please unzip (data.zip) ['MTR0MTR1.nii', 'MTR1_seg_crop.nii', and 'MNI-Poly-AMU_level.nii.gz' ]

Details:

thanh@beep:~/Desktop/bug$ sct_segment_graymatter -i MTR0MTR1.nii -s MTR1_seg_crop.nii -vert MNI-Poly-AMU_level.nii.gz -qc 0

Building the appearance model...

Loading a reduced common space (using a PCA) ...

 ---> sum of eigenvalues : 25840774.735
kept eigenvalues (PCA space dimension)  : 47

-------> IN PCA : 

-> kept_modes:[[  3.49398364e-17   1.52343914e-16  -7.58488521e-17 ...,   3.80134817e-16
   -1.89151114e-16   5.03210500e-16]
 [  8.90089761e-17  -1.19838181e-17  -1.66316223e-17 ...,   6.82225569e-16
   -5.54560867e-17   6.59016387e-16]
 [ -1.93464814e-16  -5.61873130e-16   2.97913681e-16 ...,   1.44167405e-15
   -6.91923514e-17   1.34597836e-15]
 ..., 
 [  4.82975213e-41  -1.96928854e-41   7.01142309e-42 ...,  -1.99192770e-40
    7.88297211e-41   4.54343078e-40]
 [  2.30677769e-42   1.98578340e-42  -7.86602226e-43 ...,  -2.10894907e-41
   -1.24018683e-41   1.22609524e-41]
 [ -3.60789799e-42   6.98905602e-42  -7.80287706e-43 ...,   3.91838402e-41
   -3.27249882e-42  -1.60868436e-41]]

-> kept_eigenval:47
sct_convert -i MTR0MTR1.nii -o MTR0MTR1.nii.gz
sct_convert -i MTR1_seg_crop.nii -o MTR1_seg_crop.nii.gz
mkdir tmp_MTR0MTR1_160223124221_307580/

Doing target pre-processing ...
cp MNI-Poly-AMU_level.nii.gz tmp_MTR0MTR1_160223124221_307580//MNI-Poly-AMU_level.nii.gz
cp MTR0MTR1.nii.gz tmp_MTR0MTR1_160223124221_307580//target.nii.gz
cp MTR1_seg_crop.nii.gz tmp_MTR0MTR1_160223124221_307580//target_sc_seg.nii.gz
sct_resample -i target.nii.gz -mm 0.3x0.3x5.0 -o target_resampled.nii.gz -x spline
sct_resample -i target_sc_seg.nii.gz -mm 0.3x0.3x5.0 -o target_sc_seg_resampled.nii.gz -x nn
sct_maths -i target_sc_seg_resampled.nii.gz -thr 0.0 -o target_sc_seg_resampled.nii.gz
sct_maths -i target_sc_seg_resampled.nii.gz -bin -o target_sc_seg_resampled.nii.gz
WARNING: File target_resampled.nii.gz already exists. Deleting it.
sct_image -i target_resampled.nii.gz -pad 39,39,0 -o target_resampled_pad.nii.gz
sct_image -i target_sc_seg_resampled.nii.gz -pad 39,39,0 -o target_sc_seg_resampled_pad.nii.gz
sct_image -i target_resampled_pad.nii.gz -setorient RPI -o target_resampled_pad_RPI.nii.gz
sct_image -i target_sc_seg_resampled_pad.nii.gz -setorient RPI -o target_sc_seg_resampled_pad_RPI.nii.gz
sct_crop_image -i target_resampled_pad_RPI.nii.gz -m target_sc_seg_resampled_pad_RPI.nii.gz -b 0 -o target_resampled_pad_RPI_seg_in.nii.gz
sct_create_mask -i target_resampled_pad_RPI_seg_in.nii.gz -p centerline,target_sc_seg_resampled_pad_RPI.nii.gz -size 73 -o target_resampled_pad_RPI_square_mask_from_sc_seg.nii.gz -f box

Doing target gray matter segmentation ...

Constructing target image ...
mkdir ./affine_transformations
Linear target normalization using median ...
/data/RnD/Thanh/Miniconda_MEW/build/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/data/RnD/Thanh/Miniconda_MEW/build/lib/python2.7/site-packages/numpy/core/_methods.py:71: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/data/RnD/Thanh/Miniconda_MEW/build/lib/python2.7/site-packages/numpy/core/_methods.py:83: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/data/RnD/Thanh/Miniconda_MEW/build/lib/python2.7/site-packages/numpy/core/_methods.py:95: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/data/RnD/Thanh/Miniconda_MEW/build/lib/python2.7/site-packages/numpy/core/_methods.py:117: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
WARNING: The contrast between GM and WM is too small to use the normalization based on median WM-GM values estimated with a pre-registration of the GM template, it will be replaced by a linear normalization using minimum/maximum intensity values
Linear target normalization using min-max ...
Traceback (most recent call last):
  File "/data/RnD/Thanh/spinalcord2.1/spinalcordtoolbox-2.2.2/build/sct2.2.2/scripts/sct_segment_graymatter", line 605, in <module>
    gmsegfull.segment()
  File "/data/RnD/Thanh/spinalcord2.1/spinalcordtoolbox-2.2.2/build/sct2.2.2/scripts/sct_segment_graymatter", line 287, in segment
    self.segmentation_pipeline()

[data.zip](https://github.com/neuropoly/spinalcordtoolbox/files/143091/data.zip)

**Comment by SaraDupont** [comment] 2016-02-23 18:24
I just reproduced your issue: I'm working on it, I'll let you know as soon as I have a fix.

**Comment by SaraDupont** [comment] 2016-02-23 20:33
The issue is due to the very low intensity in your first and last slices that's why the intensity normalization was failing. (There is so little information in those slices that during the registration to our model data, this information is lost and those slices appear "empty".) 

I fixed it in commit 0a1fdde which will be merged to master in the pull request #740. The function will output a GM segmentation for the first and last slices (as for the other) but keep in mind that given the intensity in those slides, the GM segmentation doesn't mean anything there. 

If you don't want to wait for a patch to fix this, you can also crop your data to remove the first and last slices. (I checked, it works)

**Comment by nguyen1j** [comment] 2016-02-23 21:19
Thank you very much.

**Closed** 2016-02-25 18:44 UTC
