### ISSUE TITLE
Create feature to remove labels by their value

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1788] opened 2018-05-29 06:00 UTC
### Description

In pipelines, it would be useful to bring labels from other contrast (e.g. from t1 to dmri) and remove them selectively (e.g., 2,3,5,6 to keep only 4). Another useful feature would be to select the label to keep.

The implementation could be:
- `sct_label_utils -i LABELS -remove-value 2,3,6,7`
- `sct_label_utils -i LABELS -keep-value 4,5`

**Comment by joshuacwnewton** [comment] 2020-10-11 22:50
Duplicate of #2247, which was addressed by #2283.

**Closed by joshuacwnewton** 2020-10-11 22:50 UTC
Labels: feature, sct_label_utils
