### ISSUE TITLE
writing permission issue

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#880] opened 2016-06-03 17:51 UTC
Issue from user (Shahab) on Ubuntu, local home folder:
"permission not allowed to write AIL.nii.gz" file.
The solution was to restart the computer.

**Comment by benjamindeleener** [comment] 2016-06-03 18:04
Is it reproducible? What are the permissions on the folder? Was the output folder (`-ofolder` option) provided?

**Comment by jcohenadad** [comment] 2016-06-03 19:07
@benjamindeleener: No, it is not reproducible. I though I would just report the error here in case this happens to another user. In this case the trick was to reboot.

**Comment by benjamindeleener** [comment] 2016-08-30 13:02
I am closing this issue because it is not reproducible. Useful if error happens again.

**Closed by benjamindeleener** 2016-08-30 13:02 UTC
Labels: bug, sct_propseg
