### ISSUE TITLE
UserWarning: Matplotlib is building the font cache using fc-list.

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#774] opened 2016-03-21 17:52 UTC
~~~
Checking test_sct_segment_graymatter................/home/travis/build/neuropoly/spinalcordtoolbox/python/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
~~~

**Comment by poquirion** [comment] 2016-03-23 16:50
I only see the warning on travis. Can't reproduce on my laptop (Ubuntu 15.10)

**Comment by SaraDupont** [comment] 2016-03-30 17:49
Just committed about this issue (commit a610ec7), is the warning still there ?

**Comment by zhengziqiang** [comment] 2016-06-12 07:39
what should I do next?

**Comment by jcohenadad** [comment] 2016-06-12 15:02
Hi @zhengziqiang, are you experiencing any error in relation to this warning message? If so, could you please indicate the command you typed, version you are running, and copy/paste of your terminal. Thanks

**Comment by SaraDupont** [comment] 2016-10-17 14:23
I no longer see the warning, I guess the multiple commits about this fixed it.

**Closed by SaraDupont** 2016-10-17 14:23 UTC
Labels: enhancement, priority: medium, sct_segment_graymatter, travis
