### ISSUE TITLE
Help menu doesn't print when running sct_deepseg command without flags

### ISSUE THREAD

**Issue by andreanne-lemay** [neuropoly/spinalcordtoolbox#3158] opened 2021-01-11 17:15 UTC
### Description

When running `sct_deepseg` command without flags, the help menu doesn't print. Instead, the code is run and an error occurs since there are no flags.

### Steps to Reproduce

Run `sct_deepseg` in terminal.

**Expected behavior:**
![image](https://user-images.githubusercontent.com/49137243/104215303-91590780-5406-11eb-8a5e-58b79c077a09.png)

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/49137243/104215176-6a9ad100-5406-11eb-8c53-87a8bd231a64.png)

**Comment by jcohenadad** [comment] 2021-01-11 17:16
duplicate of #3154

**Closed by jcohenadad** 2021-01-11 17:16 UTC
Labels: sct_deepseg
