### ISSUE TITLE
transpose_bvec not working properly

### ISSUE THREAD

**Issue by stephaniealley** [neuropoly/spinalcordtoolbox#1514] opened 2017-11-08 00:38 UTC
### Description

output same as input

compute_dti cannot be run successfully

[dmri_crop_moco.nii.gz](https://github.com/neuropoly/spinalcordtoolbox/files/1452378/dmri_crop_moco.nii.gz)
[bvecs.txt](https://github.com/neuropoly/spinalcordtoolbox/files/1452379/bvecs.txt)
[bvals.txt](https://github.com/neuropoly/spinalcordtoolbox/files/1452380/bvals.txt)

### Steps to Reproduce

sct_dmri_compute_dti -i dmri_crop_moco.nii.gz -bvec bvecs.txt -bval bvals.txt

### State of spinalcordtoolbox

Spinal Cord Toolbox (master/6976c73a4318a0acd7eb88da2d190fde73b6beb0)

### Additional Information

Running /Users/stall_admin/spinalcordtoolbox/scripts/sct_dmri_compute_dti.py -i dmri_crop_moco.nii.gz -bvec bvecs.txt -bval bvals.txt
data.shape (31, 35, 15, 34)
Traceback (most recent call last):
  File "/Users/stall_admin/spinalcordtoolbox/scripts/sct_dmri_compute_dti.py", line 209, in <module>
    main()
  File "/Users/stall_admin/spinalcordtoolbox/scripts/sct_dmri_compute_dti.py", line 102, in main
    if not compute_dti(fname_in, fname_bvals, fname_bvecs, prefix, method, file_mask):
  File "/Users/stall_admin/spinalcordtoolbox/scripts/sct_dmri_compute_dti.py", line 128, in compute_dti
    gtab = gradient_table(bvals, bvecs)
  File "/Users/stall_admin/spinalcordtoolbox/python/lib/python2.7/site-packages/dipy/core/gradients.py", line 252, in gradient_table
    atol=atol)
  File "/Users/stall_admin/spinalcordtoolbox/python/lib/python2.7/site-packages/dipy/core/gradients.py", line 140, in gradient_table_from_bvals_bvecs
    raise ValueError("bvecs should be (N, 3), a set of N unit vectors")
ValueError: bvecs should be (N, 3), a set of N unit vectors

--

**Comment by jcohenadad** [comment] 2017-11-18 02:26
@stephaniealley: the last vector of the bvecs file is [0, 0, 0], while the last value of the bvals is 800, so the issue is not related to the code, but to your bvecs/bvals files.

We can close this.

**Closed by jcohenadad** 2017-11-18 02:26 UTC
Labels: bug
