### ISSUE TITLE
[sct_process_segmentation] Error: Extract centerline

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#1118] opened 2017-01-23 22:50 UTC
Data:
```
/Volumes/data_shared/sct_testing/large/amu_G1_3/t2s/t2s_seg_manual.nii.gz
```

Syntax:
```
sct_process_segmentation -i /Volumes/data_shared/sct_testing/large/amu_G1_3/t2s/t2s_seg_manual.nii.gz -p centerline
```

Error:
```
Check parameters:
.. segmentation file:             /Users/chgroc/data/data_sdika_err/twh_e23779_t2s_seg.nii.gz

Create temporary folder...
mkdir tmp.170123163935_26341/

Copying data to tmp folder...
sct_convert -i /Users/chgroc/data/data_sdika_err/twh_e23779_t2s_seg.nii.gz -o tmp.170123163935_26341/segmentation.nii.gz

Orient centerline to RPI orientation...
sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz

Open segmentation volume...

Get data dimensions...
.. matrix size: 512 x 512 x 12
.. voxel size:  0.3906mm x 0.3906mm x 8.00003mm

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Smoothing algo = nurbs

Fitting centerline using B-spline approximation...
Test: # of control points = 5
Error on approximation = 4.72 mm
Test: # of control points = 6
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 7
Error on approximation = 36.15 mm
Test: # of control points = 8
WARNING: NURBS instability -> wrong control points
Test: # of control points = 9
singular matrix
Test: # of control points = 10
singular matrix
Test: # of control points = 11
singular matrix
The fitting of the curve was done using  5  control points: the number that gave the best results. 
Error on approximation = 4.72 mm
Traceback (most recent call last):
  File "/Users/chgroc/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 1128, in <module>
    main(sys.argv[1:])
  File "/Users/chgroc/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 226, in main
    fname_output = extract_centerline(fname_segmentation, remove_temp_files, verbose=param.verbose, algo_fitting=param.algo_fitting)
  File "/Users/chgroc/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 467, in extract_centerline
    data[int(round(x_centerline_fit[iz-min_z_index])), int(round(y_centerline_fit[iz-min_z_index])), int(iz)] = 1 # if index is out of bounds here for hanning: either the segmentation has holes or labels have been added to the file
IndexError: index 12 is out of bounds for axis 2 with size 12
```

**Comment by charleygros** [comment] 2017-01-23 22:58
The bug seems to come from `smooth_centerline`.

Concerning:
```
# if index is out of bounds here for hanning: either the segmentation has holes or labels have been added to the file
```
>> Check on the test image (given path above): segmentation file only contains 0 and 1 values and no holes in the axial plane.

**Comment by charleygros** [comment] 2017-02-01 17:55
Data:
```
/data_shared/sct_testing/large/twh_e24011/t2s/t2s_seg_manual.nii.gz
```

Command:
```
sct_process_segmentation -i t2s_seg_manual.nii.gz -p centerline 
```

Error:
```
Check parameters:
.. segmentation file:             /Users/chgroc/data/data_sdika/input_nii_t2s/twh_e23779_t2s_seg.nii.gz

Create temporary folder...
mkdir tmp.170201125139_9825/

Copying data to tmp folder...
sct_convert -i /Users/chgroc/data/data_sdika/input_nii_t2s/twh_e23779_t2s_seg.nii.gz -o tmp.170201125139_9825/segmentation.nii.gz

Orient centerline to RPI orientation...
sct_image -i segmentation.nii.gz -setorient RPI -o segmentation_RPI.nii.gz

Open segmentation volume...

Get data dimensions...
.. matrix size: 512 x 512 x 12
.. voxel size:  0.3906mm x 0.3906mm x 8.00003mm

Smooth centerline/segmentation...
.. Get center of mass of the centerline/segmentation...
.. Smoothing algo = nurbs

Fitting centerline using B-spline approximation...
Test: # of control points = 5
Error on approximation = 4.72 mm
Test: # of control points = 6
WARNING: NURBS instability -> wrong reconstruction
Test: # of control points = 7
Error on approximation = 36.15 mm
Test: # of control points = 8
WARNING: NURBS instability -> wrong control points
Test: # of control points = 9
singular matrix
Test: # of control points = 10
singular matrix
Test: # of control points = 11
singular matrix
The fitting of the curve was done using  5  control points: the number that gave the best results. 
Error on approximation = 4.72 mm
Traceback (most recent call last):
  File "/Users/chgroc/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 1210, in <module>
    main(sys.argv[1:])
  File "/Users/chgroc/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 236, in main
    fname_output = extract_centerline(fname_segmentation, remove_temp_files, verbose=param.verbose, algo_fitting=param.algo_fitting)
  File "/Users/chgroc/spinalcordtoolbox/scripts/sct_process_segmentation.py", line 549, in extract_centerline
    data[int(round(x_centerline_fit[iz-min_z_index])), int(round(y_centerline_fit[iz-min_z_index])), int(iz)] = 1 # if index is out of bounds here for hanning: either the segmentation has holes or labels have been added to the file
IndexError: index 12 is out of bounds for axis 2 with size 12
```

Merci Benjamin!

**Comment by benjamindeleener** [comment] 2017-02-04 16:26
I changed arbitrarily fixed threshold to 2 mm because it make more sense and will avoid issues on images with low number of slices, for which simple interpolation scheme is enough to have a good centerline.

**Comment by benjamindeleener** [comment] 2017-03-14 13:43
The error reappeared but was caused by the same problem than issue #1202 

This will be fixed in a PR.

**Closed** 2017-03-14 15:43 UTC
Labels: bug, priority: high, sct_process_segmentation
