### ISSUE TITLE
sct_label_verterbrae Not possible to use viewer to initialize C2-C3 disc

### ISSUE THREAD

**Issue by Nicolas-Pinon** [neuropoly/spinalcordtoolbox#2124] opened 2019-01-19 00:08 UTC
When using `sct_label_vertebrae` with flag `-initc2`, no viewer is opened to manually label C2.
I checked a bit but not for too long, the problems in my opinion lies near [this line](https://github.com/neuropoly/spinalcordtoolbox/blob/72110238094a31e29fa6f925a58ee3265825ab28/scripts/sct_label_vertebrae.py#L255) where disc_labels are obtained automatically even when the manual setting is on.

**Comment by jcohenadad** [comment] 2019-01-19 00:11
thanks for investigating @Nicolas-Pinon 
closing because duplicate of https://github.com/neuropoly/spinalcordtoolbox/issues/2120

**Closed by jcohenadad** 2019-01-19 00:11 UTC
Labels: sct_label_vertebrae
