### ISSUE TITLE
[sct_register_multimodal] Columnwise should force type=seg

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1034] opened 2016-11-21 16:54 UTC
Currently the option
``````
step=1,algo=columnwise
``````

Assumes type=im:

``````
step=1,type=im,algo=columnwise
`````

**Comment by jcohenadad** [comment] 2016-11-21 17:26
it's not a bug-- user should specify what to use with each algo.

i agree it would be better to warn the user of course.

**Comment by tanguyduval** [comment] 2016-11-21 17:35
I see, maybe we should look at the warper:
- make step and type mandatory options
- check the inputs. For instance if you do type=fdsiojfo, you need to wait the function to run until you see a bug: ````ERROR: Wrong image type````

**Comment by SaraDupont** [comment] 2016-11-24 22:24
The param 'type' is now mandatory (see PR #1048) 
Regarding the 'step' param, it's delicate since the function needs a default param that can be overwritten by the user's param, so `step=''` doesn't work.

**Comment by SaraDupont** [comment] 2016-12-05 18:07
Fixed in PR #1057

**Closed by SaraDupont** 2016-12-05 18:07 UTC
Labels: enhancement, priority: medium, sct_register_multimodal
