### ISSUE TITLE
installation is very long

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1549] opened 2017-12-06 15:06 UTC
it hangs at "Processing /Users/julien/code/sct" for ~10min. Could this be reduced?

**Comment by poquirion** [comment] 2017-12-07 16:13
@jcohenadad,
I have tied to reproduce from the tip of master but could not. It does hang on `Processing /home/poquirion/test/sct` but only for 5-10 sec. It happens at the `pip install $SCT_DIR` step, not in the sct.

**Comment by poquirion** [comment] 2017-12-07 16:15
Wait it did hang for a while once. Seems to be intermittent.

**Comment by zougloub** [comment] 2017-12-07 17:25
I'll try to reproduce the isue on my mac when back home as I don't see this when doing a full package install on Linux.
Do you have a way to trace what is blocking on your system (something like `strace`) ?

**Comment by jcohenadad** [comment] 2017-12-07 23:07
@zougloub: sorry i'm not sure how to use `strace` (i guess the mac equivalent would be `dtrace`)

**Comment by zougloub** [comment] 2018-01-18 05:29
I tried to look at the issue a few weeks ago but had some permission issues to use dtrace... will check again soon. The issue is still relevant?

**Comment by jcohenadad** [comment] 2018-01-18 06:21
on a Mac OSX 10.10.5 using version cf64e93d55cadd6ad3710dfbe7d847784ed57cbc, this step: `Processing /Users/julien/code/sct` now takes about 35s, which I guess is acceptable.
I will try on other stations and maybe we can close this issue it it remains at acceptable durations.

**Comment by zougloub** [comment] 2018-02-28 23:12
The issue is still relevant... even Travis has it on Linux.

**Comment by zougloub** [comment] 2018-03-01 02:10
Upstream pip issue: https://github.com/pypa/pip/issues/2195

**Comment by zougloub** [comment] 2018-03-01 03:36
pip v10.0.0 (not yet released) has merged https://github.com/pypa/pip/pull/4764 which is addressing the slowness issue.
In https://github.com/neuropoly/spinalcordtoolbox/commit/9ec9e866816b090cdaa74d04e2438247878afee1 I modified the installer to use the master branch of pip, until pip 10 is released. 
IMHO this shouldn't be too unsafe, but we could also access a specific commit.

**Comment by zougloub** [comment] 2018-03-01 03:45
Implemented conditional install of the pre-release.

**Closed** 2018-03-01 08:00 UTC
Labels: bug, installation, upstream
