### ISSUE TITLE
Likely some NIFTI header problem when using the viewer for initialize centerline 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2186] opened 2019-03-09 15:25 UTC
When using the viewer, the output segmentation has an offset. More information here: http://forum.spinalcordmri.org/t/deepseg-missing-the-mark/22

### To reproduce

**Data (internal server): 20190309_issue2186**

**SCT Version**
master/98357789ef916c1a10bff81d47eabffad5906aeb

**Syntax**
~~~
sct_deepseg_sc -i sanlm_structural.nii.gz -c t1 -ofolder deepseg
~~~
--> works fine

~~~
sct_deepseg_sc -i sanlm_structural.nii.gz -c t1 -ofolder deepseg.viewer -centerline viewer
~~~
--> output shifted

**Comment by charleygros** [comment] 2019-03-09 15:55
Tests with data: 20190309_issue2186

- Input and Ouput have the same q/s form.

- Idem for the fitted centerline (ie the q/s forms are the same as the ones of the input)

- Idem for the manual labels (ie the q/s forms are the same as the ones of the input)

Note: the fitted centerline and the manual labels can be output with the following command:
```
sct_deepseg_sc -i structural.nii.gz -c t1 -brain 1 -ofolder deepseg -centerline viewer -r 0 -v 2
```
after switching to the branch `cg/2168-2167-deepsegSC-manual-centerline` (https://github.com/neuropoly/spinalcordtoolbox/pull/2183).

**Comment by jcohenadad** [comment] 2019-03-09 15:56
@charleygros can you reproduce the issue observed by the user?

**Comment by charleygros** [comment] 2019-03-09 16:00
Yes I can reproduce the issue observed by the user:
![image](https://user-images.githubusercontent.com/14353425/54073911-a92e4480-42e0-11e9-8b56-09dc061b1ede.png)

**Comment by charleygros** [comment] 2019-03-09 16:22
The only difference between the input/output in the q/s forms are: `qform_name`, `qform_code`, `sform_name`, `sform_code`.

Input:
```
qform_name     Aligned Anat
qform_code     2
qto_xyz:1      1.000000  0.000000  0.000000  -123.713150
qto_xyz:2      0.000000  1.000000  0.000000  -119.320007
qto_xyz:3      0.000000  0.000000  1.000000  -116.264023
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Left-to-Right
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Aligned Anat
sform_code     2
sto_xyz:1      1.000000  0.000000  0.000000  -123.713150
sto_xyz:2      0.000000  1.000000  0.000000  -119.320007
sto_xyz:3      0.000000  0.000000  1.000000  -116.264023
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Left-to-Right
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
```

Output:
```
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      1.000000  0.000000  0.000000  -123.713150
qto_xyz:2      0.000000  1.000000  0.000000  -119.320007
qto_xyz:3      0.000000  0.000000  1.000000  -116.264023
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Left-to-Right
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Scanner Anat
sform_code     1
sto_xyz:1      1.000000  0.000000  0.000000  -123.713150
sto_xyz:2      0.000000  1.000000  0.000000  -119.320007
sto_xyz:3      0.000000  0.000000  1.000000  -116.264023
sto_xyz:4      0.000000  0.000000  0.000000  1.000000
sform_xorient  Left-to-Right
sform_yorient  Posterior-to-Anterior
sform_zorient  Inferior-to-Superior
```

@jcohenadad : What do you think about these differences?

**Comment by jcohenadad** [comment] 2019-03-09 20:11
I don't know about these differences, but there seem to be a bug in `sct_deepseg_sc.core.uncrop_image()`. See below the flip between `seg_unCrop.data` and `im_nii.data` for slice zz=20 (notice the offset):
![anim](https://user-images.githubusercontent.com/2482071/54076816-93d3fe80-427d-11e9-9d09-4d9139aea2a7.gif)

**Comment by charleygros** [comment] 2019-03-10 14:11
@jcohenadad --> I looked at the following tmp files: `image_in_RPI_resampled.nii` and `image_in_RPI_resampled_seg.nii` --> there is already an offset at this step, which means that the bug is not due to `sct_deepseg_sc.core.uncrop_image()`, but prior to it.

**Comment by charleygros** [comment] 2019-03-10 14:35
@jcohenadad : I have looked at the files (ie image overlaid with the segmentation) before `sct_deepseg_sc.core.uncrop_image()` --> there is no offset.
--> The bug is indeed certainly in `sct_deepseg_sc.core.uncrop_image()`.

**Comment by charleygros** [comment] 2019-03-13 12:24
@jcohenadad : I have looked at the files (ie image overlaid with the segmentation) before `sct_deepseg_sc.core.uncrop_image()` --> there is no offset.
--> The bug is indeed certainly in `sct_deepseg_sc.core.uncrop_image()`.

**Comment by charleygros** [comment] 2019-03-13 12:30
I think that the error comes from this line:
https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/deepseg_sc/core.py#L500
--> This line assumed that the centerline starts from z==0.
Which is NOT the case on the reported case when you use the viewer since the first slices are black --> not labels --> no centerline --> the function `sct_deepseg_sc.core.uncrop_image()` reconstructs the image with a shift in the I-S direction.

Note: when I add a label on the first slice (ie z==0) with the viewer, I do not observe a shift of the segmentation anymore. Which further confirms the above point.

This can be easily fixed by adding the z coordinates of the centerline as input.

**Closed** 2019-03-14 13:13 UTC
Labels: bug, sct_deepseg_sc
