### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type itk::ExceptionObject*

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#629] opened 2015-10-25 21:03 UTC
this happens with extension is not provided in flag "-o". We should check (maybe in the parser?)

**Comment by joshuacwnewton** [comment] 2020-10-16 15:12
I have tried to reproduce this with the following command:

```
sct_apply_transfo -i template/template/PAM50_small_t2.nii.gz -d t2/t2.nii.gz -w t2/warp_template2anat.nii.gz -o PAM50_small_t2_reg
```

(It should be `-o PAM50_small_t2_reg.nii`)

It fails, but for a different reason than is described in this issue.

```
Apply transformation and resample to destination space...
Traceback (most recent call last):
  File "/home/joshua/Repos/spinalcordtoolbox/scripts/sct_apply_transfo.py", line 381, in <module>
    main()
  File "/home/joshua/Repos/spinalcordtoolbox/scripts/sct_apply_transfo.py", line 373, in main
    transform.apply()
  File "/home/joshua/Repos/spinalcordtoolbox/scripts/sct_apply_transfo.py", line 228, in apply
    ] + fname_warp_list_invert + ['-r', fname_dest] + interp, verbose=verbose, is_sct_binary=True)
  File "/home/joshua/Repos/spinalcordtoolbox/spinalcordtoolbox/utils.py", line 721, in run_proc
    raise RuntimeError(output)
RuntimeError
```

It seems like the original description was referring to a specific C++ exception, but we now use `run_proc` with compiled binaries, which unfortunately doesn't tell us anything useful apart from a `RuntimeError`. 

https://github.com/neuropoly/spinalcordtoolbox/blob/cab82fd13425515a8568225dbe7fc003d9be2b1f/scripts/sct_apply_transfo.py#L223-L228


My gut is that this bug description is too outdated to be useful, because it is specific to the codebase in 2015. I'm closing, because we can always create a new issue if it becomes relevant again.

**Closed by joshuacwnewton** 2020-10-16 15:12 UTC
Labels: bug, sct_apply_transfo
