### ISSUE TITLE
sct_testing gets stuck + "The process has forked" message

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1898] opened 2018-07-03 18:03 UTC
~~~
sct_testing -d 1

--
Spinal Cord Toolbox (master/7ee38f84eb5e9695c9a4f459e42498bd7c684de4)
Running /Users/julien/code/sct/scripts/sct_testing.py -d 1

Downloading testing data...

Trying URL: https://osf.io/z8gaj/?action=download
Downloading 20180125_sct_testing_data.zip...
Status: 100%|###################################################| 6.78M/6.78M [00:10<00:00, 641KB/s]

Check if folder already exists...
WARNING: Folder sct_testing_data already exists. Removing it...
rm -rf sct_testing_data

Unzip data to: /Users/julien

Remove temporary file...
Done!


Path to testing data: /Users/julien/sct_testing_data
Checking sct_analyze_lesion.........................[OK]
Checking sct_analyze_texture........................[OK]
Checking sct_apply_transfo..........................[OK]
Checking sct_compute_ernst_angle....................[OK]
Checking sct_compute_hausdorff_distance.............The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
[OK]
Checking sct_compute_mtr............................[OK]
Checking sct_compute_mscc...........................[OK]
Checking sct_compute_snr............................[OK]
Checking sct_concat_transfo.........................[OK]
Checking sct_convert................................[OK]
Checking sct_create_mask............................The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
[OK]
Checking sct_crop_image.............................[OK]
Checking sct_dice_coefficient.......................[OK]
Checking sct_deepseg_gm.............................[OK]
Checking sct_deepseg_sc.............................[OK]
Checking sct_detect_pmj.............................[OK]
Checking sct_dmri_compute_dti.......................[OK]
Checking sct_dmri_concat_bvals......................[OK]
Checking sct_dmri_concat_bvecs......................[OK]
Checking sct_dmri_create_noisemask..................[OK]
Checking sct_dmri_compute_bvalue....................[OK]
Checking sct_dmri_moco..............................[OK]
Checking sct_dmri_separate_b0_and_dwi...............[OK]
Checking sct_dmri_transpose_bvecs...................[OK]
Checking sct_extract_metric.........................[OK]
Checking sct_fmri_compute_tsnr......................[OK]
Checking sct_fmri_moco..............................[OK]
Checking sct_get_centerline.........................
~~~

**Comment by jcohenadad** [comment] 2018-08-19 17:14
@zougloub this is issue is becoming a bit annoying: cannot run `sct_testing` locally unless we remove processing time output from the launcher, which is not great for our users either. Do you see a possible fix for it?

**Comment by zougloub** [comment] 2018-08-19 21:55
I suggest to remove the processing time output from the launcher. This counter doesn't add any value over what one would get running `time $cmd`.

**Comment by zougloub** [comment] 2018-08-19 21:56
Also, I'll replace the launcher with a python-based solution in #1996

**Comment by jcohenadad** [comment] 2018-08-20 15:12
well, i do find the counter useful i have to admit. It makes it a bit less ugly than to write "time $cmd" each time (for our batch pipelines). And if we don't do it systematically, sometimes we might want to get the processing time retrospectively, and it would be dumb to have to re-launch the process just to get the time.

if the python-based solution provides a workaround to keep the time, it would be great

**Comment by zougloub** [comment] 2018-08-26 23:45
Somehow I can't reproduce the problem on a Mac i have access to, but Travis has it...

**Comment by zougloub** [comment] 2018-08-27 19:47
Workaround: use `-j 1` in the sct_testing call. There's a limitation of OSX where forked programs cannot just do what they want until they `exec()`, which Python's multiprocessing doesn't do.

**Comment by jcohenadad** [comment] 2018-08-27 22:04
thanks, the workaround `-j 1` did it. 

Fun fact: after a fresh reboot `sct_testing` ran seamlessly. After re-running it a second time, I got the errors described in this issue.

**Comment by joshuacwnewton** [comment] 2020-10-11 18:20
Closing, as I believe this is outdated. `sct_launcher` is no longer used.

**Closed by joshuacwnewton** 2020-10-11 18:20 UTC
Labels: sct_testing, tests
