### ISSUE TITLE
sct_crop_image throws an error due to "sct.printv()" call

### ISSUE THREAD

**Issue by perone** [neuropoly/spinalcordtoolbox#1546] opened 2017-11-28 19:46 UTC
### Prerequisites

* [X] Did you check past issues for similar issue(s) ?
* [X] Can you reproduce the issue with any of the files found in `sct_testing_data` ?
* [X] If you are using a development environment, is your environment updated ? **Using a feature branch, but should be reproducible on master.**

### Description

`sct_crop_image` has an empty `sct.printv()` call that throws an error when reached.

### Steps to Reproduce

1. Run the `sct_crop_image` and select two points;
2. An error is shown

**Expected behavior:**

Cropping the image.

**Actual behavior:**

Error below:
```
Traceback (most recent call last):
  File "/Users/chper/Desktop/Devel/sct_deepgmseg/scripts/sct_crop_image.py", line 416, in <module>
    cropper.crop_with_gui()
  File "/Users/chper/Desktop/Devel/sct_deepgmseg/scripts/sct_crop_image.py", line 267, in crop_with_gui
    sct.printv()
TypeError: printv() takes at least 1 argument (0 given)
```

**Reproduces how often:**

Always

### State of spinalcordtoolbox

Include the first 3 lines printed when running the command.
Example:

```
$ sct_crop_image

--
Spinal Cord Toolbox (feature_deepgmseg/2649cab799ad0959060959b2b61b61cb42d7a346)
Running /Users/chper/Desktop/Devel/sct_deepgmseg/scripts/sct_crop_image.py
...
```

**Comment by jcohenadad** [comment] 2018-01-17 05:38
@perone: I was not able to reproduce with version d2cdabf6c9399174c6ccbf5885a74546d1a09d58.

Syntax:
~~~
cd sct_example_data/t2
sct_crop_image -i t2.nii.gz -g 1
~~~

It works as expected.

**Comment by jcohenadad** [comment] 2019-04-11 17:47
Closing because no followup

**Closed by jcohenadad** 2019-04-11 17:47 UTC
Labels: bug, sct_crop_image
