### ISSUE TITLE
Issues in logging vs. printing

### ISSUE THREAD

**Issue by zougloub** [neuropoly/spinalcordtoolbox#1941] opened 2018-07-17 05:59 UTC
Logging vs. printing:
- logging is typically used within library functions
- stdout/stderr printing is typically used in command-line entry points
- (note: in python's logging module, logging is performed per class/module, not per object)

In SCT, logging is mixed up with printing (when calling sub-commands, logging becomes printing) and printing is mostly emulated using logging, and that's not cool when we're thinking about providing a library API.
Current docs: https://github.com/neuropoly/spinalcordtoolbox/wiki/logging

A good solution would have to:
- have any Python API use logging exclusively, to avoid cluttering user's stdout/stderr;
- have any Python API not call SCT subprocesses (to avoid transforming logging into printing, or losing logging output);
- not take user's logging configuration for granted (just declare a logger and use it, but don't touch logging configuration or handlers in anything but front-end code);
- have front-ends that print useful info (there are long-running tasks with progress bars, and a pattern to allow logging output to be captured and transformed into printing by any front-end would be useful).

TODO examples

**Comment by jcohenadad** [comment] 2019-04-07 18:52
Related to https://github.com/neuropoly/spinalcordtoolbox/issues/2213

**Comment by jcohenadad** [comment] 2019-04-09 16:27
Duplicate of #2213

**Closed by jcohenadad** 2019-04-09 16:27 UTC
Labels: card:DESIGN_DISCUSSION
