### ISSUE TITLE
Activate SCT's Python

### ISSUE THREAD

**Issue by charleygros** [neuropoly/spinalcordtoolbox#2334] opened 2019-07-04 13:13 UTC
I am having issue when activating SCT's Python, which I did not have before.

SCT version: [last commit](https://github.com/neuropoly/spinalcordtoolbox/commit/222673d7b62936390c2ba872e12154e4a07cf82d).

Error:
```
charley@charley:~$ source ${SCT_DIR}/python/etc/profile.d/conda.sh
charley@charley:~$ conda activate venv_sct
(venv_sct) charley@charley:~$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from spinalcordtoolbox.image import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/charley/sct/spinalcordtoolbox/image.py", line 26, in <module>
    from msct_types import Coordinate
ModuleNotFoundError: No module named 'msct_types'
>>>
```

My `bashrc`:
```
# SPINALCORDTOOLBOX (installed on 2019-06-05 13:57:41)
export PATH="/home/charley/sct/bin:${PATH}"
export SCT_DIR=/home/charley/sct
export MPLBACKEND=Agg
```

**Comment by jcohenadad** [comment] 2019-07-04 13:23
@charleygros could you please try the following:
- open a new terminal
- run:
~~~
cd $SCT_DIR
git checkout master
git pull
yes | ./install_sct
~~~
- open new terminal
- run:
~~~
source ${SCT_DIR}/python/etc/profile.d/conda.sh
conda activate venv_sct
# once in python try again:
from spinalcordtoolbox.image import Image
~~~
If it does not work, please send me the entire terminal output.

**Comment by charleygros** [comment] 2019-07-04 13:34
@jcohenadad: Thank you for your quick answer, will run this and keep you posted.

Note that this issue is actually a duplication (oupsi) of #2332

**Comment by jcohenadad** [comment] 2019-07-04 14:08
@charleygros no worries!
duplicate of #2332

**Closed by jcohenadad** 2019-07-04 14:08 UTC
Labels: bug, installation
