### ISSUE TITLE
[qc] Bug trying to launch the server

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/spinalcordtoolbox#1301] opened 2017-04-29 03:15 UTC
COmmand:
`````
sct_qc -folder ~/qc_batch_processing/
`````
Bug
`````
Spinal Cord Toolbox (version: 3.0.3)
Running /Users/Tanguy/sct_3.0.3/scripts/sct_qc.py -folder /Users/Tanguy/qc_batch_processing/
Check folder existence...
Traceback (most recent call last):
  File "/Users/Tanguy/sct_3.0.3/scripts/sct_qc.py", line 58, in <module>
    _copy_assets(qc_path)
  File "/Users/Tanguy/sct_3.0.3/scripts/sct_qc.py", line 33, in _copy_assets
    shutil.copy2(os.path.join(assets_path, 'index.html'), dest_path)
  File "/Users/Tanguy/sct_3.0.3/python/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/Tanguy/sct_3.0.3/python/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/Tanguy/sct_3.0.3/assets/index.html'
`````
Data attached!
[qc.zip](https://github.com/neuropoly/spinalcordtoolbox/files/965862/qc.zip)

**Comment by benjamindeleener** [comment] 2017-04-29 03:17
Duplicate of #1300.

**Closed by benjamindeleener** 2017-04-29 03:17 UTC
Labels: bug
