### ISSUE TITLE
Limit file size on commit

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/spinalcordtoolbox#3100] opened 2020-12-16 14:18 UTC
Problem: we would like to forbid commits that include files bigger than XX MB.
Possible implementations: 

- https://stackoverflow.com/questions/39576257/how-to-limit-file-size-on-commit/39578014#39578014
- https://gist.github.com/kiwidamien/a6a909ee196be8795b30431079074d64

Crossref: https://github.com/neuropoly/axondeepseg/issues/423 https://github.com/shimming-toolbox/shimming-toolbox/issues/199 https://github.com/ivadomed/ivadomed/issues/583

**Comment by kousu** [comment] 2020-12-17 23:31
I wrote up this issue here https://github.com/neuropoly/spinalcordtoolbox/issues/2705

There, I advocated that it's better to do this in CI instead of on each user's machine, since it's easy to not have a git hook installed.

**Comment by joshuacwnewton** [comment] 2021-02-08 15:18
I'm going to close this as it's a dupe of #2705, and most discussion has gone on in that issue.

**Closed by joshuacwnewton** 2021-02-08 15:18 UTC
Labels: enhancement, good first issue
