### ISSUE TITLE
sys.path will use user site-packages over SCT conda environment's site-packages

### ISSUE THREAD

**Issue by joshuacwnewton** [neuropoly/spinalcordtoolbox#3067] opened 2020-11-30 15:59 UTC
### Context

This concerns the post **[AttributeError: ‘str’ object has no attribute ‘decode’ - v5.0.0](https://forum.spinalcordmri.org/t/attributeerror-str-object-has-no-attribute-decode-v5-0-0/567/)** from the forum.

The user in the post above has installed packages to their [user site directory](https://www.python.org/dev/peps/pep-0370/#specification). Despite SCT using a conda environment, the user site packages packages take precedent over the packages SCT installs. The specific error in the forum post happens because SCT's `h5py==2.10.0` is ignored in favor of the user's `h5py==3.1.0`. There are other package mismatches (like incorrect `pytorch` versions) which may have further consequences.

This is caused by https://github.com/conda-forge/python-feedstock/issues/171. (See also: the linked issues in the timeline for that issue.)

The best description of the issue I found was in https://github.com/mozilla/OpenWPM/issues/689.

### Discussion

1. **How can we detect this earlier?**

The reason this wasn't caught in the installation script is because we set the [`PYTHONNOUSERSITE` environment variable](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONNOUSERSITE) here:

https://github.com/neuropoly/spinalcordtoolbox/blob/d9c2d4df9c271f68c454294d576dd3ba03e9627c/install_sct#L502-L504

This change only takes effect within the scope of `./install_sct`. So, when we run `sct_check_dependencies` as part of the installation, everything _looks_ okay. But, as soon as the user finishes the installation and tries to use an SCT script, the user site packages are used, and the problem reveals itself.

The fact that `PYTHONNOUSERSITE` is set just hides the underlying problem. So, I think it might be good to unset this right before `sct_check_dependencies` is run to better reflect the user's actual environment and allow us to detect this issue.

2. **How can we prevent the user site directory from interfering long-term?**

The most prominent idea from https://github.com/conda-forge/python-feedstock/issues/171 is [to `export PYTHONNOUSERSITE=True`](https://github.com/conda-forge/python-feedstock/issues/171#issuecomment-374261534). This could be done, for example, by adding this to the user's `.bashrc`. But, this would affect more than just SCT, however, so perhaps there's a cleaner solution. 

This also ties into the ongoing discussions re: how SCT installs itself. (Bringing its own `conda` environment vs. pip installing, etc.) So, #1526 is definitely relevant here.

**Comment by Drulex** [comment] 2020-11-30 16:29
I am able to reproduce this by running `pip install --user $some_package` within the `sct` venv. This somehow adds `$HOME/.local/lib/python3.6/site-packages` to the venv python's path **permanently**.

Seems to me like a bug with the `venv` handling of `pip install --user`. The whole point of the `venv` is to avoid cross-contamination between system/user environments and dedicated virtual environments.

I'm not sure what exactly is the good way to approach this. Since we bundle this `venv` with the project we are definitely allowed to hack at it and probably tweak the sourcing scripts to avoid this specific contamination. Otherwise this should be fixed upstream (probably in a similar way?).

I don't think we should touch the install scripts. Also my current hypothesis is that this would only affect people who manually run `pip install --user` within the `venv`.

**Comment by Drulex** [comment] 2020-11-30 16:35
Well now that I re-read my comment it kinda makes sense that `conda` would add the local sites-package path to the `venv` python path if the user specifically runs `pip install --user` within the `venv`.

If we really want to avoid this we can still tweak PYTHONPATH within the venv sourcing scripts I guess.

**Comment by joshuacwnewton** [comment] 2020-11-30 16:59
> Also my current hypothesis is that this would only affect people who manually run pip install --user within the venv.

I'm not sure if whether `pip install --user` was run within the `venv` is relevant here. I believe `/home/<user>/.local/lib` only has to be present (regardless of how it was created) for it to be automatically detected and included.

See the [`site` module](https://docs.python.org/3/library/site.html#module-site) page for more info:

> **This module is automatically imported during initialization.** The automatic import can be suppressed using the interpreter’s -S option.
>
> Importing this module will append site-specific paths to the module search path and add a few builtins, unless -S was used. 

That, combined with the default UNIX value of [`site.USER_SITE`](https://docs.python.org/3/library/site.html#site.USER_SITE), is what enables this behavior, I think.

**Comment by joshuacwnewton** [comment] 2020-11-30 17:10
> Seems to me like a bug with the `venv` handling of `pip install --user`. The whole point of the `venv` is to avoid cross-contamination between system/user environments and dedicated virtual environments.

Our conda environment, `venv_sct`, isn't a Python `virtualenv`. From what I can tell, this is more of a `conda` issue.

There are some useful linked issues on https://github.com/conda-forge/python-feedstock/issues/171 and https://github.com/conda/conda/issues/448. e.g. https://github.com/mozilla/OpenWPM/issues/689 -- they might have a more complete description of the problem.

**Comment by Drulex** [comment] 2020-11-30 17:20
> I'm not sure if whether `pip install --user` was run within the `venv` is relevant here. I believe `~/.local/lib/pythonX.Y/site-packages` only has to be present (regardless of how it was created) for it to be automatically detected and included.

Woops you're right. Turns out that folder didn't exist until I tried to repro :sweat_smile:

**Comment by joshuacwnewton** [comment] 2020-11-30 18:19
This is a bit weird... even though we use a conda environment to isolate SCT's dependencies, the conda environment doesn't get activated when an SCT script is called (since SCT scripts are directly called from `$SCT_DIR/bin` due to our `PATH` modification in `.bashrc`). So, potential solutions such as the one described in https://github.com/mozilla/OpenWPM/issues/689#issuecomment-647790874 won't work for us, I think.  

I think this is a consequence of our (nonstandard) `conda` usage for packaging, more than anything.

**Comment by joshuacwnewton** [comment] 2020-12-01 15:29
One option we could consider is setting the `PYTHONNOUSERSITE` environment variable in out compatibility launcher script. We already do this for other environment variables, see here: 

https://github.com/neuropoly/spinalcordtoolbox/blob/9c3dcf6e4b59f8a19578510fb9314b2cd93bc573/spinalcordtoolbox/compat/launcher.py#L16-L25

I'll test this out to see if it fixes the issue.

**Comment by joshuacwnewton** [comment] 2020-12-01 15:52
I'm still looking into the above, but separately I have a positive observation: The user site packages will only interfere if the Python versions are the same.

SCT is tied to Python 3.6. So, if for example a user does `pip install --user h5py` and their default system Python is Python 3.8, there will be no interference.

Because of this, I think as long as we continue to use Python 3.6, this will be a very rare occurrence. (Because it is unlikely that someone will be using Python 3.6 outside of SCT.)

**Comment by Drulex** [comment] 2020-12-01 15:59
> Because of this, I think as long as we continue to use Python 3.6, this will be a very rare occurrence. (Because it is unlikely that someone will be using Python 3.6 outside of SCT.)

I wouldn't rely on this too much. The moment we upgrade `conda` the probability of occurrence will change also.

Adding a hook in the launcher seems like a good idea to me, it's the right place to do this.

**Comment by joshuacwnewton** [comment] 2020-12-01 15:59
> One option we could consider is setting the PYTHONNOUSERSITE environment variable in out compatibility launcher script. 

I installed `h5py==3.1.0` to my user site packages, then ran `sct_check_dependencies` with and without `env["PYTHONNOUSERSITE"] = "True"`.

<details>
<summary>sct_check_dependencies without setting PYTHONNOUSERSITE</summary>

```
joshua@XPS-15-9560:~$ sct_check_dependencies

--
Spinal Cord Toolbox (git-master-9c3dcf6e4b59f8a19578510fb9314b2cd93bc573*)

sct_check_dependencies 
--

SCT info:
- version: git-master-9c3dcf6e4b59f8a19578510fb9314b2cd93bc573*
- path: /home/joshua/repos/spinalcordtoolbox
OS: linux (Linux-5.4.0-54-generic-x86_64-with-debian-bullseye-sid)
CPU cores: Available: 8, Used by ITK functions: 8
RAM: Total: 7812MB, Used: 4791MB, Available: 2581MB
Check Python executable.............................[OK]
  Using bundled python 3.6.11 | packaged by conda-forge | (default, Nov 27 2020, 18:57:37) 
[GCC 9.3.0] at /home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/bin/python3.6
Check if data are installed.........................[OK]
Check if colored is installed.......................[OK] (1.4.2)
Check if dipy is installed..........................[OK] (1.3.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (3.1.0)
Check if ivadomed (2.4.0) is installed..............[OK] (2.4.0)
Check if Keras (2.1.5) is installed.................[OK] (2.1.5)
Check if matplotlib is installed....................[OK] (3.3.3)
Check if nibabel is installed.......................[OK] (3.2.1)
Check if numpy is installed.........................[OK] (1.19.4)
Check if onnxruntime (1.4.0) is installed...........[OK] (1.4.0)
Check if pandas is installed........................[OK] (1.1.4)
Check if psutil is installed........................[OK] (5.7.3)
Check if pyqt5 (5.11.3) is installed................[OK] (5.11.3)
Check if pytest is installed........................[OK] (6.1.2)
Check if pytest-cov is installed....................[OK] (__version__ = '2.10.1')
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.25.0)
Check if requirements-parser is installed...........[OK] (0.2.0)
Check if scipy is installed.........................[OK] (1.5.4)
Check if scikit-image is installed..................[OK] (0.17.2)
Check if scikit-learn is installed..................[OK] (0.23.2)
Check if tensorflow (1.5.0) is installed............[OK] (1.5.0)
Check if torch (1.5.0+cpu) is installed.............[OK] (1.5.0+cpu)
Check if torchvision (0.6.0+cpu) is installed.......[OK] (0.6.0+cpu)
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.54.0)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.26.2)
Check if pytest_console_scripts is installed........[OK]
Check if pytest-xdist is installed..................[OK] (2.1.0)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if DISPLAY variable is set....................[OK]
Check if figure can be opened with PyQt.............[OK]
```
</details>

<details>
<summary>sct_check_dependencies after setting PYTHONNOUSERSITE=True</summary>

```
joshua@XPS-15-9560:~$ sct_check_dependencies

--
Spinal Cord Toolbox (git-master-9c3dcf6e4b59f8a19578510fb9314b2cd93bc573*)

sct_check_dependencies 
--

SCT info:
- version: git-master-9c3dcf6e4b59f8a19578510fb9314b2cd93bc573*
- path: /home/joshua/repos/spinalcordtoolbox
OS: linux (Linux-5.4.0-54-generic-x86_64-with-debian-bullseye-sid)
CPU cores: Available: 8, Used by ITK functions: 8
RAM: Total: 7812MB, Used: 4813MB, Available: 2560MB
Check Python executable.............................[OK]
  Using bundled python 3.6.11 | packaged by conda-forge | (default, Nov 27 2020, 18:57:37) 
[GCC 9.3.0] at /home/joshua/repos/spinalcordtoolbox/python/envs/venv_sct/bin/python3.6
Check if data are installed.........................[OK]
Check if colored is installed.......................[OK] (1.4.2)
Check if dipy is installed..........................[OK] (1.3.0)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if ivadomed (2.4.0) is installed..............[OK] (2.4.0)
Check if Keras (2.1.5) is installed.................[OK] (2.1.5)
Check if matplotlib is installed....................[OK] (3.3.3)
Check if nibabel is installed.......................[OK] (3.2.1)
Check if numpy is installed.........................[OK] (1.19.4)
Check if onnxruntime (1.4.0) is installed...........[OK] (1.4.0)
Check if pandas is installed........................[OK] (1.1.4)
Check if psutil is installed........................[OK] (5.7.3)
Check if pyqt5 (5.11.3) is installed................[OK] (5.11.3)
Check if pytest is installed........................[OK] (6.1.2)
Check if pytest-cov is installed....................[OK] (__version__ = '2.10.1')
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.25.0)
Check if requirements-parser is installed...........[OK] (0.2.0)
Check if scipy is installed.........................[OK] (1.5.4)
Check if scikit-image is installed..................[OK] (0.17.2)
Check if scikit-learn is installed..................[OK] (0.23.2)
Check if tensorflow (1.5.0) is installed............[OK] (1.5.0)
Check if torch (1.5.0+cpu) is installed.............[OK] (1.5.0+cpu)
Check if torchvision (0.6.0+cpu) is installed.......[OK] (0.6.0+cpu)
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.54.0)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.26.2)
Check if pytest_console_scripts is installed........[OK]
Check if pytest-xdist is installed..................[OK] (2.1.0)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if DISPLAY variable is set....................[OK]
Check if figure can be opened with PyQt.............[OK]
```
</details>

So, this indeed fixes the problem. :slightly_smiling_face:

**Closed** 2020-12-01 19:56 UTC
Labels: bug, installation, needs-discussion
