### ISSUE TITLE
ImportError: cannot import name 'convert' when executing sct_utils

### ISSUE THREAD

**Issue by sercharpak** [neuropoly/spinalcordtoolbox#2757] opened 2020-06-25 09:39 UTC
### Description 

Just by executing `sct_utils` got the following error message instead of getting the usual help message:
```
Traceback (most recent call last):
  File "/home/shernand/sct_4.3/scripts/sct_utils.py", line 28, in <module>
    from sct_convert import convert
  File "/home/shernand/sct_4.3/scripts/sct_convert.py", line 23, in <module>
    import sct_utils as sct
  File "/home/shernand/sct_4.3/scripts/sct_utils.py", line 28, in <module>
    from sct_convert import convert
ImportError: cannot import name 'convert'

```
### Steps to Reproduce

0. Installed SCT 4.3 on Ubuntu 20.04.
Output of `sct_check_dependencies`:

```
--
Spinal Cord Toolbox (4.3)

SCT info:
- version: 4.3
- path: /home/shernand/sct_4.3
OS: linux (Linux-5.4.0-37-generic-x86_64-with-debian-bullseye-sid)
CPU cores: Available: 8, Used by SCT: 8
RAM: MemTotal:       32554456 kB
total        used        free      shared  buff/cache   available
Mem:          31791        6319        2826         288       22645       24750
Swap:         11442           3       11439
Check Python executable.............................[OK]
  Using bundled python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0] at /home/shernand/sct_4.3/python/envs/venv_sct/bin/python
Check if data are installed.........................[OK]
Check if numpy is installed.........................[OK] (1.18.5)
Check if colored is installed.......................[OK] (1.4.2)
Check if dipy is installed..........................[OK] (1.1.1)
Check if futures is installed.......................[OK]
Check if h5py is installed..........................[OK] (2.10.0)
Check if ivadomed (1.2.1) is installed..............[OK] (1.2.1)
Check if Keras (2.1.5) is installed.................[OK] (2.1.5)
Check if matplotlib is installed....................[OK] (3.2.1)
Check if nibabel is installed.......................[OK] (3.1.0)
Check if pandas is installed........................[OK] (1.0.4)
Check if pyqt5 (5.11.3) is installed................[OK] (5.11.3)
Check if pytest is installed........................[OK] (5.4.3)
Check if pytest-cov is installed....................[OK] (2.9.0)
Check if raven is installed.........................[OK]
Check if requests is installed......................[OK] (2.23.0)
Check if requirements-parser is installed...........[OK] (0.2.0)
Check if scipy is installed.........................[OK] (1.4.1)
Check if scikit-image is installed..................[OK] (0.17.2)
Check if scikit-learn is installed..................[OK] (0.23.1)
Check if tensorflow (1.5.0) is installed............[OK] (1.5.0)
Check if torch (1.5.0+cpu) is installed.............[OK] (1.5.0+cpu)
Check if torchvision (0.6.0+cpu) is installed.......[OK] (0.6.0+cpu)
Check if xlwt is installed..........................[OK] (1.3.0)
Check if tqdm is installed..........................[OK] (4.46.1)
Check if transforms3d is installed..................[OK] (0.3.1)
Check if urllib3 is installed.......................[OK] (1.25.9)
Check if spinalcordtoolbox is installed.............[OK]
Check ANTs compatibility with OS ...................[OK]
Check PropSeg compatibility with OS ................[OK]
Check if DISPLAY variable is set....................[OK]
Check if figure can be opened with PyQt.............[OK]
```

1. Just executing `sct_utils`

**Expected behavior:** The usage/help message

**Actual behavior:** Got this import error
```
Traceback (most recent call last):
  File "/home/shernand/sct_4.3/scripts/sct_utils.py", line 28, in <module>
    from sct_convert import convert
  File "/home/shernand/sct_4.3/scripts/sct_convert.py", line 23, in <module>
    import sct_utils as sct
  File "/home/shernand/sct_4.3/scripts/sct_utils.py", line 28, in <module>
    from sct_convert import convert
ImportError: cannot import name 'convert'

```

**Comment by jcohenadad** [comment] 2020-06-25 16:15
@sercharpak, thank you for reporting this bug. I confirm I can reproduce your issue. We will be working on a fix with the highest priority.

**Comment by jcohenadad** [comment] 2020-06-25 17:03
@saulo-p would be nice to also add an integrity test to catch that (under `testing/`)

**Comment by saulo-p** [comment] 2020-06-25 17:17
> @saulo-p would be nice to also add an integrity test to catch that (under `testing/`)

By "that" you mean checking for errors when calling `<some_script> -h` ?

**Comment by jcohenadad** [comment] 2020-06-25 17:57
yes-- this error would have been easy to catch (i'm not talking about complex integrity testing at this point-- although it would also be nice, but out of scope for this issue)

**Comment by jcohenadad** [comment] 2020-06-25 18:47
@saulo-p sorry: i should have realized this earlier: `sct_utils` is not supposed to be exposed to the users (as you rightfully noticed, there is no main...).
so the solution is easy and takes 2min: just skip the creation of a symlink for this function during installation

**Comment by jcohenadad** [comment] 2020-06-25 18:48
which also means: scrap my comment https://github.com/neuropoly/spinalcordtoolbox/issues/2757#issuecomment-649705070-- we obviously don't need an integrity test...

**Comment by saulo-p** [comment] 2020-06-25 18:58
> which also means: scrap my comment [#2757 (comment)](https://github.com/neuropoly/spinalcordtoolbox/issues/2757#issuecomment-649705070) we obviously don't need an integrity test...

I thought you originally meant to test `sct_convert`, but after your new comment, I realized that adding a new test would not catch any error that would not have been caught already.
Cool, I will change the installation instead.

**Comment by jcohenadad** [comment] 2020-06-25 19:03
to get you started: https://github.com/neuropoly/spinalcordtoolbox/blob/master/install_sct#L556

**Comment by jcohenadad** [comment] 2020-06-25 19:08
while you're at it, you could also prevent the copy of other files that should not be exposed (msct, etc.)

also: you need to be careful because some SCT functions does have system calls to sct* and msct* functions (i know it's horrible-- we are trying to eradicate them but it's always the same story: not enough time...). so pls make sure the functions you remove from the PATH are not called (otherwise it would break somewhere, and since our testing coverage is poor, we should be careful)

**Comment by kousu** [comment] 2020-06-25 19:13
> to get you started: https://github.com/neuropoly/spinalcordtoolbox/blob/master/install_sct#L556

Watch out, there's also this:

https://github.com/neuropoly/spinalcordtoolbox/blob/dce578036beb0945aeccca6d988cb0e631b5fbcb/setup.py#L63-L70

(by the way, the way I get github to do this inline-rendering of code is by using the permalink instead of `master`; and you can append -L${n} to it to extend the link to cover a region)

**Comment by jcohenadad** [comment] 2020-06-25 19:17
> Could we think about finally removing that hack there? Maybe it would be better to switch back to listing the console_scripts explicitly?

agreed!

**Comment by jcohenadad** [comment] 2020-06-25 19:18
> (by the way, the way I get github to do this inline-rendering of code is by using the permalink instead of master; and you can append -L${n} to it to extend the link to cover a region)

awesome! i was always wondering this mystery...

**Comment by saulo-p** [comment] 2020-06-25 19:34
> so the solution is easy and takes 2min: just skip the creation of a symlink for this function during installation

> while you're at it, you could also prevent the copy of other files that should not be exposed (msct, etc.)

When you say "skip the creation" and "prevent the copy" you mean having some sort of list to be ignored by the copy loop (as opposed to copying every file in `$SCT_DIR/python/envs/venv_sct/bin/*sct*`?

I'm still figuring out the installation process, but, from the `install_sct` script it seems to me that we want to avoid having `sct_utils` in the virtual environment `bin` directory in the first place, is that the direction?

**Comment by jcohenadad** [comment] 2020-06-25 19:38
the direction would be what @kousu suggested, i think

**Comment by kousu** [comment] 2020-06-26 16:42
What if you add `$SCT_DIR/python/envs/venv_sct/bin/` to the user's PATH instead of https://github.com/neuropoly/spinalcordtoolbox/blob/master/install_sct#L553-L562?

When you're developing inside of `venv_sct` (ie `conda activate venv_sct`), that is added to your PATH so that all the `console_scripts` from all the installed python packages are available, and `pip install` arranges them so that they work even when you haven't activated that venv:

```
[kousu@requiem spinalcordtoolbox]$ python/envs/venv_sct/bin/sct_dmri_moco 

--
Spinal Cord Toolbox (git-master-dce578036beb0945aeccca6d988cb0e631b5fbcb)


DESCRIPTION
  Motion correction of dMRI data. Some of the features to improve robustness were proposed in Xu et 
al. (http://dx.doi.org/10.1016/j.neuroimage.2012.11.014) and include:
  - group-wise (-g)
  - slice-wise regularized along z using polynomial function (-param). For more info about the 
    method, type: isct_antsSliceRegularizedRegistration
  - masking (-m)
  - iterative averaging of target volume
  

USAGE
sct_dmri_moco -i <file> -bvec <file>

MANDATORY ARGUMENTS
 -i <file>                    Diffusion data                
 -bvec <file>                 Bvecs file                    

OPTIONAL ARGUMENTS
 -bval <file>                 Bvals file                    
 -bvalmin <float>             B-value threshold (in s/mm2) below which data is considered as b=0.
 -g <int>                     Group nvols successive dMRI volumes for more robustness. Default 
                              value = 3
 -m <file>                    Binary mask to limit voxels considered by the registration metric.
 -param <list of: str>        Advanced parameters. Assign value with "="; Separate arguments with 
                              ","
                                poly [int]: Degree of polynomial function used for regularization 
                                  along Z. For no regularization set to 0. Default=2.
                                smooth [mm]: Smoothing kernel. Default=1.
                                metric {MI, MeanSquares, CC}: Metric used for registration. 
                                  Default=MI.
                                gradStep [float]: Searching step used by registration algorithm. 
                                  The higher the more deformation allowed. Default=1.
                                sample [None or 0-1]: Sampling rate used for registration metric. 
                                  Default=None.
                                
 -x {nn,linear,spline}        Final Interpolation. Default value = spline
 -ofolder <folder_creation>   Output folder Default value = 
MISC
 -r {0,1}                     Remove temporary files. Default value = 1
 -v {0,1,2}                   verbose: 0 = nothing, 1 = classic, 2 = expended Default value = 1

```

So if you do this you get them installed like any other program:

```
[kousu@requiem spinalcordtoolbox]$ export PATH=$PATH:`pwd`/python/envs/venv_sct/bin/
[kousu@requiem spinalcordtoolbox]$ sct_dmri_moco 

--
Spinal Cord Toolbox (git-master-dce578036beb0945aeccca6d988cb0e631b5fbcb)


DESCRIPTION
  Motion correction of dMRI data. Some of the features to improve robustness were proposed in Xu et 
al. (http://dx.doi.org/10.1016/j.neuroimage.2012.11.014) and include:
  - group-wise (-g)
  - slice-wise regularized along z using polynomial function (-param). For more info about the 
    method, type: isct_antsSliceRegularizedRegistration
  - masking (-m)
  - iterative averaging of target volume
  

USAGE
sct_dmri_moco -i <file> -bvec <file>

MANDATORY ARGUMENTS
 -i <file>                    Diffusion data                
 -bvec <file>                 Bvecs file                    

OPTIONAL ARGUMENTS
 -bval <file>                 Bvals file                    
 -bvalmin <float>             B-value threshold (in s/mm2) below which data is considered as b=0.
 -g <int>                     Group nvols successive dMRI volumes for more robustness. Default 
                              value = 3
 -m <file>                    Binary mask to limit voxels considered by the registration metric.
 -param <list of: str>        Advanced parameters. Assign value with "="; Separate arguments with 
                              ","
                                poly [int]: Degree of polynomial function used for regularization 
                                  along Z. For no regularization set to 0. Default=2.
                                smooth [mm]: Smoothing kernel. Default=1.
                                metric {MI, MeanSquares, CC}: Metric used for registration. 
                                  Default=MI.
                                gradStep [float]: Searching step used by registration algorithm. 
                                  The higher the more deformation allowed. Default=1.
                                sample [None or 0-1]: Sampling rate used for registration metric. 
                                  Default=None.
                                
 -x {nn,linear,spline}        Final Interpolation. Default value = spline
 -ofolder <folder_creation>   Output folder Default value = 
MISC
 -r {0,1}                     Remove temporary files. Default value = 1
 -v {0,1,2}                   verbose: 0 = nothing, 1 = classic, 2 = expended Default value = 1

```

The *downside* of this is that there's a lot more in the venv's bin/ than we maybe want to expose, which is, I'm assuming, why this copy loop was done in the first place?

```
[kousu@requiem spinalcordtoolbox]$ ls python/envs/venv_sct/bin/
Display all 210 possibilities? (y or n)
2to3                              dipy_recobundles                  lzma                              pyrsa-sign                        sct_denoising_onlm                sct_testing
2to3-3.6                          dipy_reslice                      lzmadec                           pyrsa-verify                      sct_detect_pmj                    sct_utils
backend-test-tools                dipy_slr                          lzmainfo                          py.test                           sct_dice_coefficient              sct_version
captoinfo                         dipy_snr_in_cc                    lzmore                            pytest                            sct_dmri_compute_bvalue           sct_warp_template
chardetect                        dipy_split                        markdown_py                       python                            sct_dmri_compute_dti              skivi
check-model                       dipy_track_local                  msct_base_classes                 python3                           sct_dmri_concat_b0_and_dwi        sqlite3
check-node                        dipy_track_pft                    msct_gmseg_utils                  python3.6                         sct_dmri_concat_bvals             sqlite3_analyzer
clear                             easy_install                      msct_multiatlas_seg               python3.6-config                  sct_dmri_concat_bvecs             tabs
convert-caffe2-to-onnx            f2py                              msct_parser                       python3.6m                        sct_dmri_create_noisemask         tclsh
convert-onnx-to-caffe2            f2py3                             msct_register                     python3.6m-config                 sct_dmri_display_bvecs            tclsh8.6
coverage                          f2py3.6                           msct_register_landmarks           python3-config                    sct_dmri_moco                     tensorboard
coverage3                         freeze_graph                      ncursesw6-config                  pyuic5                            sct_dmri_separate_b0_and_dwi      tic
coverage-3.6                      futurize                          nib-conform                       pyvenv                            sct_dmri_transpose_bvecs          tifffile
c_rehash                          google-oauthlib-tool              nib-dicomfs                       pyvenv-3.6                        sct_download_data                 toco
dipy_align_affine                 idle3                             nib-diff                          raven                             sct_extract_metric                toco_from_protos
dipy_align_syn                    idle3.6                           nib-ls                            reset                             sct_flatten_sagittal              toe
dipy_apply_transform              imageio_download_bin              nib-nifti-dx                      saved_model_cli                   sct_fmri_compute_tsnr             tput
dipy_ba                           imageio_remove_bin                nib-tck2trk                       sct_analyze_lesion                sct_fmri_moco                     tqdm
dipy_denoise_lpca                 infocmp                           nib-trk2tck                       sct_analyze_texture               sct_get_centerline                tset
dipy_denoise_mppca                infotocap                         num2words                         sct_apply_transfo                 sct_image                         unlzma
dipy_denoise_nlmeans              isct_check_detection              onnxruntime_test                  sct_check_dependencies            sct_label_utils                   unxz
dipy_fetch                        isct_convert_binary_to_trilinear  openssl                           sct_compute_ernst_angle           sct_label_vertebrae               wheel
dipy_fit_csa                      isct_get_fractional_volume        parrec2nii                        sct_compute_hausdorff_distance    sct_maths                         wish
dipy_fit_csd                      isct_minc2volume-viewer           pasteurize                        sct_compute_mscc                  sct_merge_images                  wish8.6
dipy_fit_dki                      isct_test_ants                    pip                               sct_compute_mtr                   sct_pipeline                      x86_64-conda_cos6-linux-gnu-ld
dipy_fit_dti                      isct_warpmovie_generator          pip3                              sct_compute_mtsat                 sct_pipeline_makefig              xz
dipy_fit_ivim                     ivadomed                          pydoc                             sct_compute_snr                   sct_process_segmentation          xzcat
dipy_fit_mapmri                   lsm2bin                           pydoc3                            sct_concat_transfo                sct_propseg                       xzcmp
dipy_gibbs_ringing                lzcat                             pydoc3.6                          sct_convert                       sct_qc                            xzdec
dipy_horizon                      lzcmp                             pylupdate5                        sct_create_mask                   sct_register_multimodal           xzdiff
dipy_info                         lzdiff                            pyrcc5                            sct_crop_image                    sct_register_to_template          xzegrep
dipy_labelsbundles                lzegrep                           pyrsa-decrypt                     sct_deepseg                       sct_resample                      xzfgrep
dipy_lmm                          lzfgrep                           pyrsa-encrypt                     sct_deepseg_gm                    sct_run_batch                     xzgrep
dipy_mask                         lzgrep                            pyrsa-keygen                      sct_deepseg_lesion                sct_smooth_spinalcord             xzless
dipy_median_otsu                  lzless                            pyrsa-priv2pub                    sct_deepseg_sc                    sct_straighten_spinalcord         xzmore
```

**Comment by jcohenadad** [comment] 2020-06-26 16:53
> The downside of this is that there's a lot more in the venv's bin/ than we maybe want to expose, which is, I'm assuming, why this copy loop was done in the first place?

yes indeed :-)

**Closed** 2020-07-21 15:25 UTC
