### ISSUE TITLE
when using -init # with OptiC initialization, the propagation seems to start from the center

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#1322] opened 2017-05-15 16:09 UTC
Related to: 
- https://sourceforge.net/p/spinalcordtoolbox/discussion/help/thread/70e45f83/
- https://github.com/neuropoly/spinalcordtoolbox/issues/1160
- https://github.com/neuropoly/spinalcordtoolbox/issues/1166

To reproduce:
~~~
sct_propseg -i TIA03_MPR_BF.nii.gz -c t1 -init 15
~~~

Result:
![screen shot 2017-05-15 at 12 10 34](https://cloud.githubusercontent.com/assets/2482071/26067250/84d9ba44-3967-11e7-945a-e776edc112ed.png)

**Comment by jcohenadad** [comment] 2017-05-15 16:18
Would also be nice to have the same verbose as before on isct_propseg (maybe for -v 2?)

**Comment by benjamindeleener** [comment] 2017-05-15 16:49
The issue is fixed:
![screen shot 2017-05-15 at 12 45 55](https://cloud.githubusercontent.com/assets/7757117/26068756/9b9d0920-396c-11e7-9f77-6739d1da62f9.png)

The `-init` only accepted values between 0 and 1 when providing a centerline (which is the default case with OptiC). I modified the `-init` value that is passed to `isct_propseg` and it now works.

The fix is in branch `bdl_issue1322`.

**Closed** 2017-05-20 03:21 UTC
Labels: bug, priority:HIGH, sct_propseg
