### ISSUE TITLE
error after beta install - accessing help pages

### ISSUE THREAD

**Issue by conradbn** [neuropoly/spinalcordtoolbox#575] opened 2015-10-13 13:52 UTC
Let me start out by saying I am very excited to use the new tools in 2.1 beta!  I downloaded the spinalcordtoolbox_v2.1_beta9_osx.tar.gz from the release archive and installed by running the installer.py script.  I really like the info that is being provided during install and how easy/streamlined installation has become.

I encountered the error below which seems to affect access to the man pages for all functions:
mangrove:~ conradbn$ sct_propseg -help
Traceback (most recent call last):
  File "/usr/local/spinalcordtoolbox/bin/sct_propseg", line 157, in <module>
    arguments = parser.parse(sys.argv[1:])
  File "/usr/local/spinalcordtoolbox/scripts/msct_parser.py", line 332, in parse
    self.usage.error("ERROR: argument "+arg+" does not exist. See documentation.")
  File "/usr/local/spinalcordtoolbox/scripts/msct_parser.py", line 483, in error
    self.generate(error)
  File "/usr/local/spinalcordtoolbox/scripts/msct_parser.py", line 468, in generate
    self.set_header()
  File "/usr/local/spinalcordtoolbox/scripts/msct_parser.py", line 374, in set_header
    Modified on """ + str(self.get_modif_date_time())
  File "/usr/local/spinalcordtoolbox/scripts/msct_parser.py", line 388, in get_modif_date_time
    with open(fname, mode = 'r+') as f:
IOError: [Errno 2] No such file or directory: '/usr/local/spinalcordtoolbox/bin/modif.txt'

**Comment by benjamindeleener** [comment] 2015-10-13 14:07
The issue is caused by the missing file from ```bin/``` folder in the package. I just added this file into the package creation (commit 226f041).

@conradbn, for now you can just add this file https://github.com/neuropoly/spinalcordtoolbox/blob/master/bin/modif.txt into you ```/usr/local/spinalcordtoolbox/bin/``` folder and normally everything will work.

**Comment by conradbn** [comment] 2015-10-13 14:17
Ok, seemed like that was the case.  I will put it in there.   
Just a side note, is sct_register_graymatter supposed to be in release?  Here is my list of tools
mangrove:~ conradbn$ sct_
sct_apply_transfo               sct_convert                     sct_dmri_moco                   sct_label_utils                 sct_segment_graymatter
sct_average_data_within_mask    sct_copy_header                 sct_dmri_separate_b0_and_dwi    sct_label_vertebrae             sct_smooth_spinalcord
sct_check_atlas_integrity       sct_create_mask                 sct_dmri_transpose_bvecs        sct_maths                       sct_split_data
sct_check_dependences           sct_crop_image                  sct_download_data               sct_orientation                 sct_straighten_spinalcord
sct_compute_ernst_angle         sct_dice_coefficient            sct_extract_metric              sct_process_segmentation        sct_testing
sct_compute_hausdorff_distance  sct_dmri_compute_dti            sct_flatten_sagittal            sct_propseg                     sct_warp_template
sct_compute_mtr                 sct_dmri_concat_bvals           sct_fmri_compute_tsnr           sct_register_multimodal         
sct_concat_data                 sct_dmri_concat_bvecs           sct_fmri_moco                   sct_register_to_template        
sct_concat_transfo              sct_dmri_get_bvalue             sct_get_centerline              sct_resample

**Comment by benjamindeleener** [comment] 2015-10-13 14:22
Oops, I told you something wrong. sct_register_graymatter is not in the release. You can find here how to extract metric by taking into account the internal structure of the spinal cord: https://sourceforge.net/p/spinalcordtoolbox/wiki/register_to_metric/

Don't hesitate to give us feedback on the documentation and tips&tricks on SourceForge.

I am closing this issue.

**Closed by benjamindeleener** 2015-10-13 14:22 UTC
Labels: bug, msct_parser, priority: high

**Comment by conradbn** [comment] 2015-10-13 14:25
Thanks!
