### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#746] opened 2016-02-27 20:17 UTC
data: folder_shared/sct_issues/20160227_issue746

command:
~~~
./batch.sh
~~~

~~~
Volume 123/123:
sct_apply_transfo -i dmri_T0123.nii -d target.nii -w mat_final/mat.T123Warp.nii.gz -o dmri_moco_T0123.nii -x spline

Replace failed transformations...

Merge data back along T...

Remove temporary file...
rm target.nii
Traceback (most recent call last):
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_dmri_moco", line 546, in <module>
    main()
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_dmri_moco", line 166, in main
    dmri_moco(param)
  File "/Users/julien/code/spinalcordtoolbox/bin/sct_dmri_moco", line 400, in dmri_moco
    moco.moco(param_moco)
  File "/Users/julien/code/spinalcordtoolbox/scripts/msct_moco.py", line 144, in moco
    sct.run('rm target.nii')
  File "/Users/julien/code/spinalcordtoolbox/scripts/sct_utils.py", line 80, in run
    process = subprocess.Popen(cmd, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/Users/julien/miniconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/julien/miniconda/lib/python2.7/subprocess.py", line 1223, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/Users/julien/miniconda/lib/python2.7/subprocess.py", line 1175, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files
~~~

**Comment by jcohenadad** [comment] 2016-02-27 20:44
did not reproduce under pycharm.

**Comment by jcohenadad** [comment] 2016-02-27 20:58
error seems to be related to output of sct.run().

**Comment by jcohenadad** [comment] 2016-02-27 21:03
temporarily fixed by changing
~~~
sct.run('rm target.nii')
~~~
to
~~~
os.remove('target.nii')
~~~

but better fix should be done on sct.run.

**Comment by jcohenadad** [comment] 2016-03-01 19:22
This issue needs to be fixed by better handling open processes in Python (make sure the previous ones are closed, etc.)

**Comment by jcohenadad** [comment] 2016-03-10 18:18
this needs to be fixed at the nibabel level, see patch from @poquirion

**Comment by SaraDupont** [comment] 2016-03-11 17:37
I refactored the code using concat_data() in several scripts, and included Benjamin's approach to concatenate data faster (100 by 100 instead of 1 by 1). See if the issue is fixed by this or not.

**Comment by jcohenadad** [comment] 2016-03-11 17:52
it is fixed :-)

**Closed** 2016-03-11 17:52 UTC
Labels: bug, sct_dmri_moco, sct_utils
