### ISSUE TITLE
compile new ANTs binaries to include new version of antsSliceRegularizedRegistration

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#953] opened 2016-08-08 23:40 UTC
now includes z-rotations regularized along z

**Comment by jcohenadad** [comment] 2016-08-25 17:24
compile on Mountain Lion (monk) and Debian (ferguson) to ensure cross-compatibility

**Comment by joshuacwnewton** [comment] 2020-10-15 17:56
At this point, this is a duplicate of #1178.

**Closed by joshuacwnewton** 2020-10-15 17:56 UTC
Labels: enhancement, installation, priority:MEDIUM
