### ISSUE TITLE
warping field is "turning" at the edge of the FOV

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#475] opened 2015-08-25 13:49 UTC
Data: batch_processing
Branch: dev

Is it introduced by the straightening? Or is could it be an effect of combining warping fields?

![screen shot 2015-08-25 at 09 24 08](https://cloud.githubusercontent.com/assets/2482071/9468229/79986d68-4b0e-11e5-8038-4f0840fabc35.png)

**Comment by benjamindeleener** [comment] 2015-08-25 13:55
It is a problem with the straightening, probably caused by the fact that T2w images are not large in the left-right direction, and that warping field are null at the edges.
This issue was related but not completely fixed here: issue #463 

Padding the image at some point would probably fix the issue.

**Comment by benjamindeleener** [comment] 2015-08-25 14:26
I checked, this issue is produced by straightening process:
```
sct_straighten_spinalcord -i errsm_17_t2.nii.gz -c errsm_17_t2_manual_segmentation.nii.gz
sct_apply_transfo -i errsm_17_t2_straight.nii.gz -w warp_straight2curve.nii.gz -d errsm_17_t2.nii.gz -o test.nii.gz
fslview errsm_17_t2.nii.gz test.nii.gz &
```
<img width="117" alt="screen shot 2015-08-25 at 10 24 15" src="https://cloud.githubusercontent.com/assets/7757117/9469187/b2f6a0ca-4b13-11e5-9fb6-00eea502bb17.png">
<img width="121" alt="screen shot 2015-08-25 at 10 24 21" src="https://cloud.githubusercontent.com/assets/7757117/9469186/b2f54a86-4b13-11e5-9770-47ebb06c6a71.png">

**Comment by benjamindeleener** [comment] 2015-08-25 14:49
Tests:
```
sct_straighten_spinalcord -i errsm_17_t2.nii.gz -c errsm_17_t2_manual_segmentation.nii.gz -p 50
sct_apply_transfo -i errsm_17_t2_straight.nii.gz -w warp_straight2curve.nii.gz -d errsm_17_t2.nii.gz -o test.nii.gz
fslview errsm_17_t2.nii.gz test.nii.gz &
```
114 seconds
![benjamindeleener_2](https://cloud.githubusercontent.com/assets/7757117/9469661/429811b2-4b16-11e5-9d01-fa9b0bfba848.gif)

```
sct_straighten_spinalcord -i errsm_17_t2.nii.gz -c errsm_17_t2_manual_segmentation.nii.gz -p 100
sct_apply_transfo -i errsm_17_t2_straight.nii.gz -w warp_straight2curve.nii.gz -d errsm_17_t2.nii.gz -o test.nii.gz
fslview errsm_17_t2.nii.gz test.nii.gz &
```
227 seconds
![benjamindeleener_3](https://cloud.githubusercontent.com/assets/7757117/9469749/c56e9066-4b16-11e5-947b-90d5f4b731fb.gif)

So even when using a large padding as option, the result still is "turning". And increasing even more the padding is not an option because of time increase.

**Comment by jcohenadad** [comment] 2015-08-25 14:54
Is the padding done in the 3 directions?

I would be interested to see the result of the cross-labels straightened (the one at the edge of the image, where it is supposed to "turn"). Maybe it is a matter of bspline order?

**Comment by benjamindeleener** [comment] 2015-08-25 14:58
I tried to change the reference image of warping field generation in straight to curve direction. I've put the curved landmarks (padded) as reference.

But it doesn't change anything...

**Comment by benjamindeleener** [comment] 2015-08-25 14:58
Yes the padding is done in three directions. It could be interesting to increase the paddin only in left-right direction.

**Comment by benjamindeleener** [comment] 2015-08-25 15:13
When padding in only left-right direction, the process time decrease and the results are better. Still need to find a good image width for straightening

**Comment by jcohenadad** [comment] 2015-08-25 15:17
can you output the crosses? i would find it useful for debugging (wrt. warping field)

**Comment by benjamindeleener** [comment] 2015-08-25 15:19
It is possible to go into temp folder (with -r option) and apply the transformation to landmarks. Do you want an option to output directly the crosses for debugging?

**Comment by jcohenadad** [comment] 2015-08-25 15:21
just go to the tmp folder and apply the warping field-- no need for a flag

**Comment by benjamindeleener** [comment] 2015-08-25 15:31
Labels seem correct. It is the transform that doesn't seem good. Labels are not all there because some get out of original anat image, but they are still used for computing the bspline transformation.
![image](https://cloud.githubusercontent.com/assets/7757117/9471101/c6092c06-4b1c-11e5-9bcb-e67d7327a746.png)

**Comment by jcohenadad** [comment] 2015-08-25 15:43
in ANTSUseLandmarkImagesToGetBSplineDisplacementField, do you have enforceStationaryBoundaries=0?

For the labels: i was more thinking of having a figure with the representation of the crosses after the application of the warping field in the "straight cross" space (i.e., with all crosses present)

**Comment by jcohenadad** [comment] 2015-08-25 15:46
We had similar problem in the past-- this was due to enforceStationaryBoundaries flag:
![screen shot 2015-08-25 at 11 45 52](https://cloud.githubusercontent.com/assets/2482071/9471554/f0844252-4b1e-11e5-847f-a16b17fd6483.png)

**Comment by benjamindeleener** [comment] 2015-08-25 15:47
Yes the option enforceStationaryBoundaries is set to 0.
By the way, sct_straighten_spinalcord is now using the binary isct_ANTSLandmarksBSplineTransform instead of isct_ANTSUseLandmarkImagesToGetBSplineDisplacementField.

The warping field in the straight space is very good and we don't see the issue appearing. The issue is only in the curved space (straight to curve transformation).

**Comment by benjamindeleener** [comment] 2015-08-25 15:51
I fixed the issue. As I suspected, changin the pattern of crosses fixed the issue. It was an instability problem caused by the lack of landmarks inside the image.
I added internal crosses, like this:
![image](https://cloud.githubusercontent.com/assets/7757117/9471661/5e492ae6-4b1f-11e5-8d29-86def2a863f8.png)

And the resulting image is very good, better than before.
![benjamindeleener_4](https://cloud.githubusercontent.com/assets/7757117/9471699/9107d9d2-4b1f-11e5-9f6e-8c43d52076dc.gif)

**Comment by jcohenadad** [comment] 2015-08-25 15:52
GREAT! :+1:

**Comment by benjamindeleener** [comment] 2015-08-25 15:53
I will still let the possibility to pad in the left-right direction.

**Comment by benjamindeleener** [comment] 2015-08-25 16:12
Works fine on batch_processing data:
![image](https://cloud.githubusercontent.com/assets/7757117/9472309/85185568-4b22-11e5-8b0a-3341086dfb03.png)

Will be merged to dev as soon as all tests pass.

**Closed** 2015-08-25 17:03 UTC
Labels: sct_register_to_template
